/* Generated by re2c 0.9.1-C on Fri Oct  7 21:47:22 2022
 */
#line 1 "c.re"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#define	ADDEQ	257
#define	ANDAND	258
#define	ANDEQ	259
#define	ARRAY	260
#define	ASM	261
#define	AUTO	262
#define	BREAK	263
#define	CASE	264
#define	CHAR	265
#define	CONST	266
#define	CONTINUE	267
#define	DECR	268
#define	DEFAULT	269
#define	DEREF	270
#define	DIVEQ	271
#define	DO	272
#define	DOUBLE	273
#define	ELLIPSIS	274
#define	ELSE	275
#define	ENUM	276
#define	EQL	277
#define	EXTERN	278
#define	FCON	279
#define	FLOAT	280
#define	FOR	281
#define	FUNCTION	282
#define	GEQ	283
#define	GOTO	284
#define	ICON	285
#define	ID	286
#define	IF	287
#define	INCR	288
#define	INT	289
#define	LEQ	290
#define	LONG	291
#define	LSHIFT	292
#define	LSHIFTEQ	293
#define	MODEQ	294
#define	MULEQ	295
#define	NEQ	296
#define	OREQ	297
#define	OROR	298
#define	POINTER	299
#define	REGISTER	300
#define	RETURN	301
#define	RSHIFT	302
#define	RSHIFTEQ	303
#define	SCON	304
#define	SHORT	305
#define	SIGNED	306
#define	SIZEOF	307
#define	STATIC	308
#define	STRUCT	309
#define	SUBEQ	310
#define	SWITCH	311
#define	TYPEDEF	312
#define	UNION	313
#define	UNSIGNED	314
#define	VOID	315
#define	VOLATILE	316
#define	WHILE	317
#define	XOREQ	318
#define	EOI	319

typedef unsigned int uint;
typedef unsigned char uchar;

#define	BSIZE	8192

#define	YYCTYPE		uchar
#define	YYCURSOR	cursor
#define	YYLIMIT		s->lim
#define	YYMARKER	s->ptr
#define	YYFILL(n)	{cursor = fill(s, cursor);}

#define	RET(i)	{s->cur = cursor; return i;}

typedef struct Scanner {
    int			fd;
    uchar		*bot, *tok, *ptr, *cur, *pos, *lim, *top, *eof;
    uint		line;
} Scanner;

uchar *fill(Scanner *s, uchar *cursor){
    if(!s->eof){
	uint cnt = s->tok - s->bot;
	if(cnt){
	    memcpy(s->bot, s->tok, s->lim - s->tok);
	    s->tok = s->bot;
	    s->ptr -= cnt;
	    cursor -= cnt;
	    s->pos -= cnt;
	    s->lim -= cnt;
	}
	if((s->top - s->lim) < BSIZE){
	    uchar *buf = (uchar*) malloc(((s->lim - s->bot) + BSIZE)*sizeof(uchar));
	    memcpy(buf, s->tok, s->lim - s->tok);
	    s->tok = buf;
	    s->ptr = &buf[s->ptr - s->bot];
	    cursor = &buf[cursor - s->bot];
	    s->pos = &buf[s->pos - s->bot];
	    s->lim = &buf[s->lim - s->bot];
	    s->top = &s->lim[BSIZE];
	    free(s->bot);
	    s->bot = buf;
	}
	if((cnt = read(s->fd, (char*) s->lim, BSIZE)) != BSIZE){
	    s->eof = &s->lim[cnt]; *(s->eof)++ = '\n';
	}
	s->lim += cnt;
    }
    return cursor;
}

int scan(Scanner *s){
	uchar *cursor = s->cur;
std:
	s->tok = cursor;
#line 133 "c.re"



#line 130 "c.c"
{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy0;
	++YYCURSOR;
yy0:
	if((YYLIMIT - YYCURSOR) < 9) YYFILL(9);
	yych = *YYCURSOR;
	switch(yych){
	case '\t':	case '\v':
	case '\f':	case ' ':	goto yy73;
	case '\n':	goto yy75;
	case '!':	goto yy49;
	case '"':	goto yy28;
	case '%':	goto yy39;
	case '&':	goto yy41;
	case '\'':	goto yy24;
	case '(':	goto yy61;
	case ')':	goto yy63;
	case '*':	goto yy37;
	case '+':	goto yy33;
	case ',':	goto yy57;
	case '-':	goto yy35;
	case '.':	goto yy26;
	case '/':	goto yy2;
	case '0':	goto yy21;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy23;
	case ':':	goto yy59;
	case ';':	goto yy51;
	case '<':	goto yy31;
	case '=':	goto yy47;
	case '>':	goto yy29;
	case '?':	goto yy71;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	case '_':	case 'h':	case 'j':
	case 'k':	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':	case 'x':
	case 'y':
	case 'z':	goto yy20;
	case '[':	goto yy65;
	case ']':	goto yy67;
	case '^':	goto yy43;
	case 'a':	goto yy4;
	case 'b':	goto yy6;
	case 'c':	goto yy7;
	case 'd':	goto yy8;
	case 'e':	goto yy9;
	case 'f':	goto yy10;
	case 'g':	goto yy11;
	case 'i':	goto yy12;
	case 'l':	goto yy13;
	case 'r':	goto yy14;
	case 's':	goto yy15;
	case 't':	goto yy16;
	case 'u':	goto yy17;
	case 'v':	goto yy18;
	case 'w':	goto yy19;
	case '{':	goto yy53;
	case '|':	goto yy45;
	case '}':	goto yy55;
	case '~':	goto yy69;
	default:	goto yy77;
	}
yy2:	yych = *++YYCURSOR;
	if(yych == '*')	goto yy341;
	if(yych == '=')	goto yy339;
	goto yy3;
yy3:
#line 222 "c.re"
{ RET('/'); }
#line 236 "c.c"
yy4:	yych = *++YYCURSOR;
	if(yych == 'u')	goto yy335;
	goto yy180;
yy5:
#line 171 "c.re"
{ RET(ID); }
#line 243 "c.c"
yy6:	yych = *++YYCURSOR;
	if(yych == 'r')	goto yy330;
	goto yy180;
yy7:	yych = *++YYCURSOR;
	if(yych <= 'g'){
		if(yych == 'a')	goto yy311;
		goto yy180;
	} else {
		if(yych <= 'h')	goto yy312;
		if(yych == 'o')	goto yy313;
		goto yy180;
	}
yy8:	yych = *++YYCURSOR;
	if(yych == 'e')	goto yy297;
	if(yych == 'o')	goto yy298;
	goto yy180;
yy9:	yych = *++YYCURSOR;
	if(yych <= 'm'){
		if(yych == 'l')	goto yy283;
		goto yy180;
	} else {
		if(yych <= 'n')	goto yy284;
		if(yych == 'x')	goto yy285;
		goto yy180;
	}
yy10:	yych = *++YYCURSOR;
	if(yych == 'l')	goto yy275;
	if(yych == 'o')	goto yy276;
	goto yy180;
yy11:	yych = *++YYCURSOR;
	if(yych == 'o')	goto yy271;
	goto yy180;
yy12:	yych = *++YYCURSOR;
	if(yych == 'f')	goto yy266;
	if(yych == 'n')	goto yy268;
	goto yy180;
yy13:	yych = *++YYCURSOR;
	if(yych == 'o')	goto yy262;
	goto yy180;
yy14:	yych = *++YYCURSOR;
	if(yych == 'e')	goto yy249;
	goto yy180;
yy15:	yych = *++YYCURSOR;
	if(yych <= 's'){
		if(yych <= 'g')	goto yy180;
		if(yych <= 'h')	goto yy216;
		if(yych <= 'i')	goto yy217;
		goto yy180;
	} else {
		if(yych <= 't')	goto yy218;
		if(yych == 'w')	goto yy219;
		goto yy180;
	}
yy16:	yych = *++YYCURSOR;
	if(yych == 'y')	goto yy209;
	goto yy180;
yy17:	yych = *++YYCURSOR;
	if(yych == 'n')	goto yy197;
	goto yy180;
yy18:	yych = *++YYCURSOR;
	if(yych == 'o')	goto yy186;
	goto yy180;
yy19:	yych = *++YYCURSOR;
	if(yych == 'h')	goto yy181;
	goto yy180;
yy20:	yych = *++YYCURSOR;
	goto yy180;
yy21:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= 'X'){
		if(yych <= 'T'){
			if(yych == 'L')	goto yy155;
			goto yy171;
		} else {
			if(yych <= 'U')	goto yy155;
			if(yych <= 'W')	goto yy171;
			goto yy172;
		}
	} else {
		if(yych <= 't'){
			if(yych == 'l')	goto yy155;
			goto yy171;
		} else {
			if(yych <= 'u')	goto yy155;
			if(yych == 'x')	goto yy172;
			goto yy171;
		}
	}
yy22:
#line 175 "c.re"
{ RET(ICON); }
#line 335 "c.c"
yy23:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy153;
yy24:	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych != '\n')	goto yy143;
	goto yy25;
yy25:
#line 241 "c.re"
{
		printf("unexpected character: %c\n", *s->tok);
		goto std;
	    }
#line 349 "c.c"
yy26:	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '.')	goto yy131;
	if(yych <= '/')	goto yy27;
	if(yych <= '9')	goto yy132;
	goto yy27;
yy27:
#line 215 "c.re"
{ RET('.'); }
#line 359 "c.c"
yy28:	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '\n')	goto yy25;
	goto yy121;
yy29:	yych = *++YYCURSOR;
	if(yych <= '<')	goto yy30;
	if(yych <= '=')	goto yy114;
	if(yych <= '>')	goto yy116;
	goto yy30;
yy30:
#line 225 "c.re"
{ RET('>'); }
#line 372 "c.c"
yy31:	yych = *++YYCURSOR;
	if(yych <= ';')	goto yy32;
	if(yych <= '<')	goto yy110;
	if(yych <= '=')	goto yy108;
	goto yy32;
yy32:
#line 224 "c.re"
{ RET('<'); }
#line 381 "c.c"
yy33:	yych = *++YYCURSOR;
	if(yych == '+')	goto yy104;
	if(yych == '=')	goto yy106;
	goto yy34;
yy34:
#line 220 "c.re"
{ RET('+'); }
#line 389 "c.c"
yy35:	yych = *++YYCURSOR;
	if(yych <= '<'){
		if(yych == '-')	goto yy100;
		goto yy36;
	} else {
		if(yych <= '=')	goto yy102;
		if(yych <= '>')	goto yy98;
		goto yy36;
	}
yy36:
#line 219 "c.re"
{ RET('-'); }
#line 402 "c.c"
yy37:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy96;
	goto yy38;
yy38:
#line 221 "c.re"
{ RET('*'); }
#line 409 "c.c"
yy39:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy94;
	goto yy40;
yy40:
#line 223 "c.re"
{ RET('%'); }
#line 416 "c.c"
yy41:	yych = *++YYCURSOR;
	if(yych == '&')	goto yy90;
	if(yych == '=')	goto yy92;
	goto yy42;
yy42:
#line 216 "c.re"
{ RET('&'); }
#line 424 "c.c"
yy43:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy88;
	goto yy44;
yy44:
#line 226 "c.re"
{ RET('^'); }
#line 431 "c.c"
yy45:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy86;
	if(yych == '|')	goto yy84;
	goto yy46;
yy46:
#line 227 "c.re"
{ RET('|'); }
#line 439 "c.c"
yy47:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy82;
	goto yy48;
yy48:
#line 210 "c.re"
{ RET('='); }
#line 446 "c.c"
yy49:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy80;
	goto yy50;
yy50:
#line 217 "c.re"
{ RET('!'); }
#line 453 "c.c"
yy51:	yych = *++YYCURSOR;
	goto yy52;
yy52:
#line 205 "c.re"
{ RET(';'); }
#line 459 "c.c"
yy53:	yych = *++YYCURSOR;
	goto yy54;
yy54:
#line 206 "c.re"
{ RET('{'); }
#line 465 "c.c"
yy55:	yych = *++YYCURSOR;
	goto yy56;
yy56:
#line 207 "c.re"
{ RET('}'); }
#line 471 "c.c"
yy57:	yych = *++YYCURSOR;
	goto yy58;
yy58:
#line 208 "c.re"
{ RET(','); }
#line 477 "c.c"
yy59:	yych = *++YYCURSOR;
	goto yy60;
yy60:
#line 209 "c.re"
{ RET(':'); }
#line 483 "c.c"
yy61:	yych = *++YYCURSOR;
	goto yy62;
yy62:
#line 211 "c.re"
{ RET('('); }
#line 489 "c.c"
yy63:	yych = *++YYCURSOR;
	goto yy64;
yy64:
#line 212 "c.re"
{ RET(')'); }
#line 495 "c.c"
yy65:	yych = *++YYCURSOR;
	goto yy66;
yy66:
#line 213 "c.re"
{ RET('['); }
#line 501 "c.c"
yy67:	yych = *++YYCURSOR;
	goto yy68;
yy68:
#line 214 "c.re"
{ RET(']'); }
#line 507 "c.c"
yy69:	yych = *++YYCURSOR;
	goto yy70;
yy70:
#line 218 "c.re"
{ RET('~'); }
#line 513 "c.c"
yy71:	yych = *++YYCURSOR;
	goto yy72;
yy72:
#line 228 "c.re"
{ RET('?'); }
#line 519 "c.c"
yy73:	yych = *++YYCURSOR;
	goto yy79;
yy74:
#line 231 "c.re"
{ goto std; }
#line 525 "c.c"
yy75:	yych = *++YYCURSOR;
	goto yy76;
yy76:
#line 234 "c.re"
{
		if(cursor == s->eof) RET(EOI);
		s->pos = cursor; s->line++;
		goto std;
	    }
#line 535 "c.c"
yy77:	yych = *++YYCURSOR;
	goto yy25;
yy78:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy79;
yy79:	if(yych <= '\n'){
		if(yych == '\t')	goto yy78;
		goto yy74;
	} else {
		if(yych <= '\f')	goto yy78;
		if(yych == ' ')	goto yy78;
		goto yy74;
	}
yy80:	yych = *++YYCURSOR;
	goto yy81;
yy81:
#line 204 "c.re"
{ RET(NEQ); }
#line 555 "c.c"
yy82:	yych = *++YYCURSOR;
	goto yy83;
yy83:
#line 203 "c.re"
{ RET(EQL); }
#line 561 "c.c"
yy84:	yych = *++YYCURSOR;
	goto yy85;
yy85:
#line 200 "c.re"
{ RET(OROR); }
#line 567 "c.c"
yy86:	yych = *++YYCURSOR;
	goto yy87;
yy87:
#line 193 "c.re"
{ RET(OREQ); }
#line 573 "c.c"
yy88:	yych = *++YYCURSOR;
	goto yy89;
yy89:
#line 192 "c.re"
{ RET(XOREQ); }
#line 579 "c.c"
yy90:	yych = *++YYCURSOR;
	goto yy91;
yy91:
#line 199 "c.re"
{ RET(ANDAND); }
#line 585 "c.c"
yy92:	yych = *++YYCURSOR;
	goto yy93;
yy93:
#line 191 "c.re"
{ RET(ANDEQ); }
#line 591 "c.c"
yy94:	yych = *++YYCURSOR;
	goto yy95;
yy95:
#line 190 "c.re"
{ RET(MODEQ); }
#line 597 "c.c"
yy96:	yych = *++YYCURSOR;
	goto yy97;
yy97:
#line 188 "c.re"
{ RET(MULEQ); }
#line 603 "c.c"
yy98:	yych = *++YYCURSOR;
	goto yy99;
yy99:
#line 198 "c.re"
{ RET(DEREF); }
#line 609 "c.c"
yy100:	yych = *++YYCURSOR;
	goto yy101;
yy101:
#line 197 "c.re"
{ RET(DECR); }
#line 615 "c.c"
yy102:	yych = *++YYCURSOR;
	goto yy103;
yy103:
#line 187 "c.re"
{ RET(SUBEQ); }
#line 621 "c.c"
yy104:	yych = *++YYCURSOR;
	goto yy105;
yy105:
#line 196 "c.re"
{ RET(INCR); }
#line 627 "c.c"
yy106:	yych = *++YYCURSOR;
	goto yy107;
yy107:
#line 186 "c.re"
{ RET(ADDEQ); }
#line 633 "c.c"
yy108:	yych = *++YYCURSOR;
	goto yy109;
yy109:
#line 201 "c.re"
{ RET(LEQ); }
#line 639 "c.c"
yy110:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy112;
	goto yy111;
yy111:
#line 195 "c.re"
{ RET(LSHIFT); }
#line 646 "c.c"
yy112:	yych = *++YYCURSOR;
	goto yy113;
yy113:
#line 185 "c.re"
{ RET(LSHIFTEQ); }
#line 652 "c.c"
yy114:	yych = *++YYCURSOR;
	goto yy115;
yy115:
#line 202 "c.re"
{ RET(GEQ); }
#line 658 "c.c"
yy116:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy118;
	goto yy117;
yy117:
#line 194 "c.re"
{ RET(RSHIFT); }
#line 665 "c.c"
yy118:	yych = *++YYCURSOR;
	goto yy119;
yy119:
#line 184 "c.re"
{ RET(RSHIFTEQ); }
#line 671 "c.c"
yy120:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy121;
yy121:	if(yych <= '!'){
		if(yych != '\n')	goto yy120;
		goto yy122;
	} else {
		if(yych <= '"')	goto yy124;
		if(yych == '\\')	goto yy123;
		goto yy120;
	}
yy122:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy22;
	case 3:	goto yy134;
	case 2:	goto yy27;
	case 1:	goto yy25;
	}
yy123:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'b'){
		if(yych <= '7'){
			if(yych <= '&'){
				if(yych == '"')	goto yy120;
				goto yy122;
			} else {
				if(yych <= '\'')	goto yy120;
				if(yych <= '/')	goto yy122;
				goto yy127;
			}
		} else {
			if(yych <= '['){
				if(yych == '?')	goto yy120;
				goto yy122;
			} else {
				if(yych <= '\\')	goto yy120;
				if(yych <= '`')	goto yy122;
				goto yy120;
			}
		}
	} else {
		if(yych <= 'r'){
			if(yych <= 'm'){
				if(yych == 'f')	goto yy120;
				goto yy122;
			} else {
				if(yych <= 'n')	goto yy120;
				if(yych <= 'q')	goto yy122;
				goto yy120;
			}
		} else {
			if(yych <= 'u'){
				if(yych == 't')	goto yy120;
				goto yy122;
			} else {
				if(yych <= 'v')	goto yy120;
				if(yych == 'x')	goto yy126;
				goto yy122;
			}
		}
	}
yy124:	yych = *++YYCURSOR;
	goto yy125;
yy125:
#line 181 "c.re"
{ RET(SCON); }
#line 740 "c.c"
yy126:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy122;
		if(yych <= '9')	goto yy129;
		goto yy122;
	} else {
		if(yych <= 'F')	goto yy129;
		if(yych <= '`')	goto yy122;
		if(yych <= 'f')	goto yy129;
		goto yy122;
	}
yy127:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy128;
yy128:	if(yych <= '"'){
		if(yych == '\n')	goto yy122;
		if(yych <= '!')	goto yy120;
		goto yy124;
	} else {
		if(yych <= '7'){
			if(yych <= '/')	goto yy120;
			goto yy127;
		} else {
			if(yych == '\\')	goto yy123;
			goto yy120;
		}
	}
yy129:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy130;
yy130:	if(yych <= '9'){
		if(yych <= '!'){
			if(yych == '\n')	goto yy122;
			goto yy120;
		} else {
			if(yych <= '"')	goto yy124;
			if(yych <= '/')	goto yy120;
			goto yy129;
		}
	} else {
		if(yych <= '['){
			if(yych <= '@')	goto yy120;
			if(yych <= 'F')	goto yy129;
			goto yy120;
		} else {
			if(yych <= '\\')	goto yy123;
			if(yych <= '`')	goto yy120;
			if(yych <= 'f')	goto yy129;
			goto yy120;
		}
	}
yy131:	yych = *++YYCURSOR;
	if(yych == '.')	goto yy140;
	goto yy122;
yy132:	yyaccept = 3;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	goto yy133;
yy133:	if(yych <= 'K'){
		if(yych <= 'D'){
			if(yych <= '/')	goto yy134;
			if(yych <= '9')	goto yy132;
			goto yy134;
		} else {
			if(yych <= 'E')	goto yy135;
			if(yych <= 'F')	goto yy136;
			goto yy134;
		}
	} else {
		if(yych <= 'e'){
			if(yych <= 'L')	goto yy136;
			if(yych >= 'e')	goto yy135;
			goto yy134;
		} else {
			if(yych <= 'f')	goto yy136;
			if(yych == 'l')	goto yy136;
			goto yy134;
		}
	}
yy134:
#line 178 "c.re"
{ RET(FCON); }
#line 828 "c.c"
yy135:	yych = *++YYCURSOR;
	if(yych <= ','){
		if(yych == '+')	goto yy137;
		goto yy122;
	} else {
		if(yych <= '-')	goto yy137;
		if(yych <= '/')	goto yy122;
		if(yych <= '9')	goto yy138;
		goto yy122;
	}
yy136:	yych = *++YYCURSOR;
	goto yy134;
yy137:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy122;
	if(yych >= ':')	goto yy122;
	goto yy138;
yy138:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy139;
yy139:	if(yych <= 'K'){
		if(yych <= '9'){
			if(yych <= '/')	goto yy134;
			goto yy138;
		} else {
			if(yych == 'F')	goto yy136;
			goto yy134;
		}
	} else {
		if(yych <= 'f'){
			if(yych <= 'L')	goto yy136;
			if(yych <= 'e')	goto yy134;
			goto yy136;
		} else {
			if(yych == 'l')	goto yy136;
			goto yy134;
		}
	}
yy140:	yych = *++YYCURSOR;
	goto yy141;
yy141:
#line 183 "c.re"
{ RET(ELLIPSIS); }
#line 872 "c.c"
yy142:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy143;
yy143:	if(yych <= '&'){
		if(yych == '\n')	goto yy122;
		goto yy142;
	} else {
		if(yych <= '\'')	goto yy145;
		if(yych != '\\')	goto yy142;
		goto yy144;
	}
yy144:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'b'){
		if(yych <= '7'){
			if(yych <= '&'){
				if(yych == '"')	goto yy142;
				goto yy122;
			} else {
				if(yych <= '\'')	goto yy142;
				if(yych <= '/')	goto yy122;
				goto yy147;
			}
		} else {
			if(yych <= '['){
				if(yych == '?')	goto yy142;
				goto yy122;
			} else {
				if(yych <= '\\')	goto yy142;
				if(yych <= '`')	goto yy122;
				goto yy142;
			}
		}
	} else {
		if(yych <= 'r'){
			if(yych <= 'm'){
				if(yych == 'f')	goto yy142;
				goto yy122;
			} else {
				if(yych <= 'n')	goto yy142;
				if(yych <= 'q')	goto yy122;
				goto yy142;
			}
		} else {
			if(yych <= 'u'){
				if(yych == 't')	goto yy142;
				goto yy122;
			} else {
				if(yych <= 'v')	goto yy142;
				if(yych == 'x')	goto yy146;
				goto yy122;
			}
		}
	}
yy145:	yych = *++YYCURSOR;
	goto yy22;
yy146:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy122;
		if(yych <= '9')	goto yy149;
		goto yy122;
	} else {
		if(yych <= 'F')	goto yy149;
		if(yych <= '`')	goto yy122;
		if(yych <= 'f')	goto yy149;
		goto yy122;
	}
yy147:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy148;
yy148:	if(yych <= '\''){
		if(yych == '\n')	goto yy122;
		if(yych <= '&')	goto yy142;
		goto yy145;
	} else {
		if(yych <= '7'){
			if(yych <= '/')	goto yy142;
			goto yy147;
		} else {
			if(yych == '\\')	goto yy144;
			goto yy142;
		}
	}
yy149:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy150;
yy150:	if(yych <= '9'){
		if(yych <= '&'){
			if(yych == '\n')	goto yy122;
			goto yy142;
		} else {
			if(yych <= '\'')	goto yy145;
			if(yych <= '/')	goto yy142;
			goto yy149;
		}
	} else {
		if(yych <= '['){
			if(yych <= '@')	goto yy142;
			if(yych <= 'F')	goto yy149;
			goto yy142;
		} else {
			if(yych <= '\\')	goto yy144;
			if(yych <= '`')	goto yy142;
			if(yych <= 'f')	goto yy149;
			goto yy142;
		}
	}
yy151:	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'E')	goto yy162;
	if(yych == 'e')	goto yy162;
	goto yy161;
yy152:	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	goto yy153;
yy153:	if(yych <= 'L'){
		if(yych <= '9'){
			if(yych == '.')	goto yy151;
			if(yych <= '/')	goto yy22;
			goto yy152;
		} else {
			if(yych == 'E')	goto yy154;
			if(yych <= 'K')	goto yy22;
			goto yy155;
		}
	} else {
		if(yych <= 'e'){
			if(yych == 'U')	goto yy155;
			if(yych <= 'd')	goto yy22;
			goto yy154;
		} else {
			if(yych <= 'l'){
				if(yych <= 'k')	goto yy22;
				goto yy155;
			} else {
				if(yych == 'u')	goto yy155;
				goto yy22;
			}
		}
	}
yy154:	yych = *++YYCURSOR;
	if(yych <= ','){
		if(yych == '+')	goto yy157;
		goto yy122;
	} else {
		if(yych <= '-')	goto yy157;
		if(yych <= '/')	goto yy122;
		if(yych <= '9')	goto yy158;
		goto yy122;
	}
yy155:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy156;
yy156:	if(yych <= 'U'){
		if(yych == 'L')	goto yy155;
		if(yych <= 'T')	goto yy22;
		goto yy155;
	} else {
		if(yych <= 'l'){
			if(yych <= 'k')	goto yy22;
			goto yy155;
		} else {
			if(yych == 'u')	goto yy155;
			goto yy22;
		}
	}
yy157:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy122;
	if(yych >= ':')	goto yy122;
	goto yy158;
yy158:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy159;
yy159:	if(yych <= 'K'){
		if(yych <= '9'){
			if(yych <= '/')	goto yy134;
			goto yy158;
		} else {
			if(yych == 'F')	goto yy136;
			goto yy134;
		}
	} else {
		if(yych <= 'f'){
			if(yych <= 'L')	goto yy136;
			if(yych <= 'e')	goto yy134;
			goto yy136;
		} else {
			if(yych == 'l')	goto yy136;
			goto yy134;
		}
	}
yy160:	yyaccept = 3;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	goto yy161;
yy161:	if(yych <= 'K'){
		if(yych <= 'D'){
			if(yych <= '/')	goto yy134;
			if(yych <= '9')	goto yy160;
			goto yy134;
		} else {
			if(yych <= 'E')	goto yy166;
			if(yych <= 'F')	goto yy136;
			goto yy134;
		}
	} else {
		if(yych <= 'e'){
			if(yych <= 'L')	goto yy136;
			if(yych <= 'd')	goto yy134;
			goto yy166;
		} else {
			if(yych <= 'f')	goto yy136;
			if(yych == 'l')	goto yy136;
			goto yy134;
		}
	}
yy162:	yych = *++YYCURSOR;
	if(yych <= ','){
		if(yych != '+')	goto yy122;
		goto yy163;
	} else {
		if(yych <= '-')	goto yy163;
		if(yych <= '/')	goto yy122;
		if(yych <= '9')	goto yy164;
		goto yy122;
	}
yy163:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy122;
	if(yych >= ':')	goto yy122;
	goto yy164;
yy164:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy165;
yy165:	if(yych <= 'K'){
		if(yych <= '9'){
			if(yych <= '/')	goto yy134;
			goto yy164;
		} else {
			if(yych == 'F')	goto yy136;
			goto yy134;
		}
	} else {
		if(yych <= 'f'){
			if(yych <= 'L')	goto yy136;
			if(yych <= 'e')	goto yy134;
			goto yy136;
		} else {
			if(yych == 'l')	goto yy136;
			goto yy134;
		}
	}
yy166:	yych = *++YYCURSOR;
	if(yych <= ','){
		if(yych != '+')	goto yy122;
		goto yy167;
	} else {
		if(yych <= '-')	goto yy167;
		if(yych <= '/')	goto yy122;
		if(yych <= '9')	goto yy168;
		goto yy122;
	}
yy167:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy122;
	if(yych >= ':')	goto yy122;
	goto yy168;
yy168:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy169;
yy169:	if(yych <= 'K'){
		if(yych <= '9'){
			if(yych <= '/')	goto yy134;
			goto yy168;
		} else {
			if(yych == 'F')	goto yy136;
			goto yy134;
		}
	} else {
		if(yych <= 'f'){
			if(yych <= 'L')	goto yy136;
			if(yych <= 'e')	goto yy134;
			goto yy136;
		} else {
			if(yych == 'l')	goto yy136;
			goto yy134;
		}
	}
yy170:	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	goto yy171;
yy171:	if(yych <= 'L'){
		if(yych <= '9'){
			if(yych == '.')	goto yy151;
			if(yych <= '/')	goto yy22;
			goto yy170;
		} else {
			if(yych == 'E')	goto yy154;
			if(yych <= 'K')	goto yy22;
			goto yy177;
		}
	} else {
		if(yych <= 'e'){
			if(yych == 'U')	goto yy177;
			if(yych <= 'd')	goto yy22;
			goto yy154;
		} else {
			if(yych <= 'l'){
				if(yych <= 'k')	goto yy22;
				goto yy177;
			} else {
				if(yych == 'u')	goto yy177;
				goto yy22;
			}
		}
	}
yy172:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy122;
		if(yych >= ':')	goto yy122;
		goto yy173;
	} else {
		if(yych <= 'F')	goto yy173;
		if(yych <= '`')	goto yy122;
		if(yych >= 'g')	goto yy122;
		goto yy173;
	}
yy173:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy174;
yy174:	if(yych <= 'T'){
		if(yych <= '@'){
			if(yych <= '/')	goto yy22;
			if(yych <= '9')	goto yy173;
			goto yy22;
		} else {
			if(yych <= 'F')	goto yy173;
			if(yych != 'L')	goto yy22;
			goto yy175;
		}
	} else {
		if(yych <= 'k'){
			if(yych <= 'U')	goto yy175;
			if(yych <= '`')	goto yy22;
			if(yych <= 'f')	goto yy173;
			goto yy22;
		} else {
			if(yych <= 'l')	goto yy175;
			if(yych != 'u')	goto yy22;
			goto yy175;
		}
	}
yy175:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy176;
yy176:	if(yych <= 'U'){
		if(yych == 'L')	goto yy175;
		if(yych <= 'T')	goto yy22;
		goto yy175;
	} else {
		if(yych <= 'l'){
			if(yych <= 'k')	goto yy22;
			goto yy175;
		} else {
			if(yych == 'u')	goto yy175;
			goto yy22;
		}
	}
yy177:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy178;
yy178:	if(yych <= 'U'){
		if(yych == 'L')	goto yy177;
		if(yych <= 'T')	goto yy22;
		goto yy177;
	} else {
		if(yych <= 'l'){
			if(yych <= 'k')	goto yy22;
			goto yy177;
		} else {
			if(yych == 'u')	goto yy177;
			goto yy22;
		}
	}
yy179:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy180;
yy180:	if(yych <= 'Z'){
		if(yych <= '/')	goto yy5;
		if(yych <= '9')	goto yy179;
		if(yych <= '@')	goto yy5;
		goto yy179;
	} else {
		if(yych <= '_'){
			if(yych <= '^')	goto yy5;
			goto yy179;
		} else {
			if(yych <= '`')	goto yy5;
			if(yych <= 'z')	goto yy179;
			goto yy5;
		}
	}
yy181:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy180;
	goto yy182;
yy182:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy180;
	goto yy183;
yy183:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy180;
	goto yy184;
yy184:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy185;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy185;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy185;
		} else {
			if(yych <= '`')	goto yy185;
			if(yych <= 'z')	goto yy179;
			goto yy185;
		}
	}
yy185:
#line 169 "c.re"
{ RET(WHILE); }
#line 1320 "c.c"
yy186:	yych = *++YYCURSOR;
	if(yych == 'i')	goto yy187;
	if(yych == 'l')	goto yy188;
	goto yy180;
yy187:	yych = *++YYCURSOR;
	if(yych == 'd')	goto yy195;
	goto yy180;
yy188:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy180;
	goto yy189;
yy189:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy180;
	goto yy190;
yy190:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy180;
	goto yy191;
yy191:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy180;
	goto yy192;
yy192:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy180;
	goto yy193;
yy193:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy194;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy194;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy194;
		} else {
			if(yych <= '`')	goto yy194;
			if(yych <= 'z')	goto yy179;
			goto yy194;
		}
	}
yy194:
#line 168 "c.re"
{ RET(VOLATILE); }
#line 1362 "c.c"
yy195:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy196;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy196;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy196;
		} else {
			if(yych <= '`')	goto yy196;
			if(yych <= 'z')	goto yy179;
			goto yy196;
		}
	}
yy196:
#line 167 "c.re"
{ RET(VOID); }
#line 1382 "c.c"
yy197:	yych = *++YYCURSOR;
	if(yych == 'i')	goto yy198;
	if(yych == 's')	goto yy199;
	goto yy180;
yy198:	yych = *++YYCURSOR;
	if(yych == 'o')	goto yy206;
	goto yy180;
yy199:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy180;
	goto yy200;
yy200:	yych = *++YYCURSOR;
	if(yych != 'g')	goto yy180;
	goto yy201;
yy201:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy180;
	goto yy202;
yy202:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy180;
	goto yy203;
yy203:	yych = *++YYCURSOR;
	if(yych != 'd')	goto yy180;
	goto yy204;
yy204:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy205;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy205;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy205;
		} else {
			if(yych <= '`')	goto yy205;
			if(yych <= 'z')	goto yy179;
			goto yy205;
		}
	}
yy205:
#line 166 "c.re"
{ RET(UNSIGNED); }
#line 1424 "c.c"
yy206:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy180;
	goto yy207;
yy207:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy208;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy208;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy208;
		} else {
			if(yych <= '`')	goto yy208;
			if(yych <= 'z')	goto yy179;
			goto yy208;
		}
	}
yy208:
#line 165 "c.re"
{ RET(UNION); }
#line 1447 "c.c"
yy209:	yych = *++YYCURSOR;
	if(yych != 'p')	goto yy180;
	goto yy210;
yy210:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy180;
	goto yy211;
yy211:	yych = *++YYCURSOR;
	if(yych != 'd')	goto yy180;
	goto yy212;
yy212:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy180;
	goto yy213;
yy213:	yych = *++YYCURSOR;
	if(yych != 'f')	goto yy180;
	goto yy214;
yy214:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy215;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy215;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy215;
		} else {
			if(yych <= '`')	goto yy215;
			if(yych <= 'z')	goto yy179;
			goto yy215;
		}
	}
yy215:
#line 164 "c.re"
{ RET(TYPEDEF); }
#line 1482 "c.c"
yy216:	yych = *++YYCURSOR;
	if(yych == 'o')	goto yy245;
	goto yy180;
yy217:	yych = *++YYCURSOR;
	if(yych == 'g')	goto yy235;
	if(yych == 'z')	goto yy236;
	goto yy180;
yy218:	yych = *++YYCURSOR;
	if(yych == 'a')	goto yy225;
	if(yych == 'r')	goto yy226;
	goto yy180;
yy219:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy180;
	goto yy220;
yy220:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy180;
	goto yy221;
yy221:	yych = *++YYCURSOR;
	if(yych != 'c')	goto yy180;
	goto yy222;
yy222:	yych = *++YYCURSOR;
	if(yych != 'h')	goto yy180;
	goto yy223;
yy223:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy224;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy224;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy224;
		} else {
			if(yych <= '`')	goto yy224;
			if(yych <= 'z')	goto yy179;
			goto yy224;
		}
	}
yy224:
#line 163 "c.re"
{ RET(SWITCH); }
#line 1525 "c.c"
yy225:	yych = *++YYCURSOR;
	if(yych == 't')	goto yy231;
	goto yy180;
yy226:	yych = *++YYCURSOR;
	if(yych != 'u')	goto yy180;
	goto yy227;
yy227:	yych = *++YYCURSOR;
	if(yych != 'c')	goto yy180;
	goto yy228;
yy228:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy180;
	goto yy229;
yy229:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy230;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy230;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy230;
		} else {
			if(yych <= '`')	goto yy230;
			if(yych <= 'z')	goto yy179;
			goto yy230;
		}
	}
yy230:
#line 162 "c.re"
{ RET(STRUCT); }
#line 1557 "c.c"
yy231:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy180;
	goto yy232;
yy232:	yych = *++YYCURSOR;
	if(yych != 'c')	goto yy180;
	goto yy233;
yy233:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy234;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy234;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy234;
		} else {
			if(yych <= '`')	goto yy234;
			if(yych <= 'z')	goto yy179;
			goto yy234;
		}
	}
yy234:
#line 161 "c.re"
{ RET(STATIC); }
#line 1583 "c.c"
yy235:	yych = *++YYCURSOR;
	if(yych == 'n')	goto yy241;
	goto yy180;
yy236:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy180;
	goto yy237;
yy237:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy180;
	goto yy238;
yy238:	yych = *++YYCURSOR;
	if(yych != 'f')	goto yy180;
	goto yy239;
yy239:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy240;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy240;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy240;
		} else {
			if(yych <= '`')	goto yy240;
			if(yych <= 'z')	goto yy179;
			goto yy240;
		}
	}
yy240:
#line 160 "c.re"
{ RET(SIZEOF); }
#line 1615 "c.c"
yy241:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy180;
	goto yy242;
yy242:	yych = *++YYCURSOR;
	if(yych != 'd')	goto yy180;
	goto yy243;
yy243:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy244;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy244;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy244;
		} else {
			if(yych <= '`')	goto yy244;
			if(yych <= 'z')	goto yy179;
			goto yy244;
		}
	}
yy244:
#line 159 "c.re"
{ RET(SIGNED); }
#line 1641 "c.c"
yy245:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy180;
	goto yy246;
yy246:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy180;
	goto yy247;
yy247:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy248;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy248;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy248;
		} else {
			if(yych <= '`')	goto yy248;
			if(yych <= 'z')	goto yy179;
			goto yy248;
		}
	}
yy248:
#line 158 "c.re"
{ RET(SHORT); }
#line 1667 "c.c"
yy249:	yych = *++YYCURSOR;
	if(yych == 'g')	goto yy250;
	if(yych == 't')	goto yy251;
	goto yy180;
yy250:	yych = *++YYCURSOR;
	if(yych == 'i')	goto yy256;
	goto yy180;
yy251:	yych = *++YYCURSOR;
	if(yych != 'u')	goto yy180;
	goto yy252;
yy252:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy180;
	goto yy253;
yy253:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy180;
	goto yy254;
yy254:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy255;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy255;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy255;
		} else {
			if(yych <= '`')	goto yy255;
			if(yych <= 'z')	goto yy179;
			goto yy255;
		}
	}
yy255:
#line 157 "c.re"
{ RET(RETURN); }
#line 1703 "c.c"
yy256:	yych = *++YYCURSOR;
	if(yych != 's')	goto yy180;
	goto yy257;
yy257:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy180;
	goto yy258;
yy258:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy180;
	goto yy259;
yy259:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy180;
	goto yy260;
yy260:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy261;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy261;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy261;
		} else {
			if(yych <= '`')	goto yy261;
			if(yych <= 'z')	goto yy179;
			goto yy261;
		}
	}
yy261:
#line 156 "c.re"
{ RET(REGISTER); }
#line 1735 "c.c"
yy262:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy180;
	goto yy263;
yy263:	yych = *++YYCURSOR;
	if(yych != 'g')	goto yy180;
	goto yy264;
yy264:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy265;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy265;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy265;
		} else {
			if(yych <= '`')	goto yy265;
			if(yych <= 'z')	goto yy179;
			goto yy265;
		}
	}
yy265:
#line 155 "c.re"
{ RET(LONG); }
#line 1761 "c.c"
yy266:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy267;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy267;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy267;
		} else {
			if(yych <= '`')	goto yy267;
			if(yych <= 'z')	goto yy179;
			goto yy267;
		}
	}
yy267:
#line 153 "c.re"
{ RET(IF); }
#line 1781 "c.c"
yy268:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy180;
	goto yy269;
yy269:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy270;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy270;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy270;
		} else {
			if(yych <= '`')	goto yy270;
			if(yych <= 'z')	goto yy179;
			goto yy270;
		}
	}
yy270:
#line 154 "c.re"
{ RET(INT); }
#line 1804 "c.c"
yy271:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy180;
	goto yy272;
yy272:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy180;
	goto yy273;
yy273:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy274;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy274;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy274;
		} else {
			if(yych <= '`')	goto yy274;
			if(yych <= 'z')	goto yy179;
			goto yy274;
		}
	}
yy274:
#line 152 "c.re"
{ RET(GOTO); }
#line 1830 "c.c"
yy275:	yych = *++YYCURSOR;
	if(yych == 'o')	goto yy279;
	goto yy180;
yy276:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy180;
	goto yy277;
yy277:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy278;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy278;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy278;
		} else {
			if(yych <= '`')	goto yy278;
			if(yych <= 'z')	goto yy179;
			goto yy278;
		}
	}
yy278:
#line 151 "c.re"
{ RET(FOR); }
#line 1856 "c.c"
yy279:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy180;
	goto yy280;
yy280:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy180;
	goto yy281;
yy281:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy282;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy282;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy282;
		} else {
			if(yych <= '`')	goto yy282;
			if(yych <= 'z')	goto yy179;
			goto yy282;
		}
	}
yy282:
#line 150 "c.re"
{ RET(FLOAT); }
#line 1882 "c.c"
yy283:	yych = *++YYCURSOR;
	if(yych == 's')	goto yy294;
	goto yy180;
yy284:	yych = *++YYCURSOR;
	if(yych == 'u')	goto yy291;
	goto yy180;
yy285:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy180;
	goto yy286;
yy286:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy180;
	goto yy287;
yy287:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy180;
	goto yy288;
yy288:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy180;
	goto yy289;
yy289:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy290;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy290;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy290;
		} else {
			if(yych <= '`')	goto yy290;
			if(yych <= 'z')	goto yy179;
			goto yy290;
		}
	}
yy290:
#line 149 "c.re"
{ RET(EXTERN); }
#line 1920 "c.c"
yy291:	yych = *++YYCURSOR;
	if(yych != 'm')	goto yy180;
	goto yy292;
yy292:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy293;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy293;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy293;
		} else {
			if(yych <= '`')	goto yy293;
			if(yych <= 'z')	goto yy179;
			goto yy293;
		}
	}
yy293:
#line 148 "c.re"
{ RET(ENUM); }
#line 1943 "c.c"
yy294:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy180;
	goto yy295;
yy295:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy296;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy296;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy296;
		} else {
			if(yych <= '`')	goto yy296;
			if(yych <= 'z')	goto yy179;
			goto yy296;
		}
	}
yy296:
#line 147 "c.re"
{ RET(ELSE); }
#line 1966 "c.c"
yy297:	yych = *++YYCURSOR;
	if(yych == 'f')	goto yy305;
	goto yy180;
yy298:	yych = *++YYCURSOR;
	if(yych <= '^'){
		if(yych <= '9'){
			if(yych >= '0')	goto yy179;
			goto yy299;
		} else {
			if(yych <= '@')	goto yy299;
			if(yych <= 'Z')	goto yy179;
			goto yy299;
		}
	} else {
		if(yych <= 't'){
			if(yych != '`')	goto yy179;
			goto yy299;
		} else {
			if(yych <= 'u')	goto yy300;
			if(yych <= 'z')	goto yy179;
			goto yy299;
		}
	}
yy299:
#line 145 "c.re"
{ RET(DO); }
#line 1993 "c.c"
yy300:	yych = *++YYCURSOR;
	if(yych != 'b')	goto yy180;
	goto yy301;
yy301:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy180;
	goto yy302;
yy302:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy180;
	goto yy303;
yy303:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy304;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy304;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy304;
		} else {
			if(yych <= '`')	goto yy304;
			if(yych <= 'z')	goto yy179;
			goto yy304;
		}
	}
yy304:
#line 146 "c.re"
{ RET(DOUBLE); }
#line 2022 "c.c"
yy305:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy180;
	goto yy306;
yy306:	yych = *++YYCURSOR;
	if(yych != 'u')	goto yy180;
	goto yy307;
yy307:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy180;
	goto yy308;
yy308:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy180;
	goto yy309;
yy309:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy310;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy310;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy310;
		} else {
			if(yych <= '`')	goto yy310;
			if(yych <= 'z')	goto yy179;
			goto yy310;
		}
	}
yy310:
#line 144 "c.re"
{ RET(DEFAULT); }
#line 2054 "c.c"
yy311:	yych = *++YYCURSOR;
	if(yych == 's')	goto yy327;
	goto yy180;
yy312:	yych = *++YYCURSOR;
	if(yych == 'a')	goto yy324;
	goto yy180;
yy313:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy180;
	goto yy314;
yy314:	yych = *++YYCURSOR;
	if(yych <= 'r')	goto yy180;
	if(yych <= 's')	goto yy315;
	if(yych <= 't')	goto yy316;
	goto yy180;
yy315:	yych = *++YYCURSOR;
	if(yych == 't')	goto yy322;
	goto yy180;
yy316:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy180;
	goto yy317;
yy317:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy180;
	goto yy318;
yy318:	yych = *++YYCURSOR;
	if(yych != 'u')	goto yy180;
	goto yy319;
yy319:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy180;
	goto yy320;
yy320:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy321;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy321;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy321;
		} else {
			if(yych <= '`')	goto yy321;
			if(yych <= 'z')	goto yy179;
			goto yy321;
		}
	}
yy321:
#line 143 "c.re"
{ RET(CONTINUE); }
#line 2103 "c.c"
yy322:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy323;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy323;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy323;
		} else {
			if(yych <= '`')	goto yy323;
			if(yych <= 'z')	goto yy179;
			goto yy323;
		}
	}
yy323:
#line 142 "c.re"
{ RET(CONST); }
#line 2123 "c.c"
yy324:	yych = *++YYCURSOR;
	if(yych != 'r')	goto yy180;
	goto yy325;
yy325:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy326;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy326;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy326;
		} else {
			if(yych <= '`')	goto yy326;
			if(yych <= 'z')	goto yy179;
			goto yy326;
		}
	}
yy326:
#line 141 "c.re"
{ RET(CHAR); }
#line 2146 "c.c"
yy327:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy180;
	goto yy328;
yy328:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy329;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy329;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy329;
		} else {
			if(yych <= '`')	goto yy329;
			if(yych <= 'z')	goto yy179;
			goto yy329;
		}
	}
yy329:
#line 140 "c.re"
{ RET(CASE); }
#line 2169 "c.c"
yy330:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy180;
	goto yy331;
yy331:	yych = *++YYCURSOR;
	if(yych != 'a')	goto yy180;
	goto yy332;
yy332:	yych = *++YYCURSOR;
	if(yych != 'k')	goto yy180;
	goto yy333;
yy333:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy334;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy334;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy334;
		} else {
			if(yych <= '`')	goto yy334;
			if(yych <= 'z')	goto yy179;
			goto yy334;
		}
	}
yy334:
#line 139 "c.re"
{ RET(BREAK); }
#line 2198 "c.c"
yy335:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy180;
	goto yy336;
yy336:	yych = *++YYCURSOR;
	if(yych != 'o')	goto yy180;
	goto yy337;
yy337:	yych = *++YYCURSOR;
	if(yych <= 'Z'){
		if(yych <= '/')	goto yy338;
		if(yych <= '9')	goto yy179;
		if(yych >= 'A')	goto yy179;
		goto yy338;
	} else {
		if(yych <= '_'){
			if(yych >= '_')	goto yy179;
			goto yy338;
		} else {
			if(yych <= '`')	goto yy338;
			if(yych <= 'z')	goto yy179;
			goto yy338;
		}
	}
yy338:
#line 138 "c.re"
{ RET(AUTO); }
#line 2224 "c.c"
yy339:	yych = *++YYCURSOR;
	goto yy340;
yy340:
#line 189 "c.re"
{ RET(DIVEQ); }
#line 2230 "c.c"
yy341:	yych = *++YYCURSOR;
	goto yy342;
yy342:
#line 136 "c.re"
{ goto comment; }
#line 2236 "c.c"
}
#line 245 "c.re"


comment:

#line 2243 "c.c"
{
	YYCTYPE yych;
	goto yy343;
	++YYCURSOR;
yy343:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych == '\n')	goto yy347;
	if(yych != '*')	goto yy349;
	goto yy345;
yy345:	yych = *++YYCURSOR;
	if(yych == '/')	goto yy350;
	goto yy346;
yy346:
#line 256 "c.re"
{ goto comment; }
#line 2260 "c.c"
yy347:	yych = *++YYCURSOR;
	goto yy348;
yy348:
#line 251 "c.re"
{
		if(cursor == s->eof) RET(EOI);
		s->tok = s->pos = cursor; s->line++;
		goto comment;
	    }
#line 2270 "c.c"
yy349:	yych = *++YYCURSOR;
	goto yy346;
yy350:	yych = *++YYCURSOR;
	goto yy351;
yy351:
#line 249 "c.re"
{ goto std; }
#line 2278 "c.c"
}
#line 257 "c.re"

}

main(){
    Scanner in;
    int t;
    memset((char*) &in, 0, sizeof(in));
    in.fd = 0;
    while((t = scan(&in)) != EOI){
/*
	printf("%d\t%.*s\n", t, in.cur - in.tok, in.tok);
	printf("%d\n", t);
*/
    }
    close(in.fd);
}
