/* Generated by re2c 0.9.1-C on Fri Oct  7 22:36:33 2022
 */
#line 1 "repeater.re"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#define RET(n) printf("%d\n", n); return n

int scan(char *s, int l){
char *p = s;
char *q;
#define YYCTYPE         char
#define YYCURSOR        p
#define YYLIMIT         (s+l)
#define YYMARKER        q
#define YYFILL(n)

#line 19 "repeater.c"
{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy0;
	++YYCURSOR;
yy0:
	if((YYLIMIT - YYCURSOR) < 7) YYFILL(7);
	yych = *YYCURSOR;
	if(yych <= '`'){
		if(yych == 'A')	goto yy3;
		goto yy6;
	} else {
		if(yych <= 'a')	goto yy5;
		if(yych != 'q')	goto yy6;
		goto yy2;
	}
yy2:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy4;
	}
yy3:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '@'){
		if(yych == '\n')	goto yy8;
		goto yy4;
	} else {
		if(yych <= 'A')	goto yy7;
		if(yych == 'a')	goto yy7;
		goto yy4;
	}
yy4:
#line 20 "repeater.re"
{RET(0);}
#line 53 "repeater.c"
yy5:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych == '\n')	goto yy8;
		goto yy2;
	} else {
		if(yych <= 'A')	goto yy7;
		if(yych == 'a')	goto yy7;
		goto yy2;
	}
yy6:	yych = *++YYCURSOR;
	goto yy4;
yy7:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych == '\n')	goto yy11;
		goto yy2;
	} else {
		if(yych <= 'A')	goto yy10;
		if(yych == 'a')	goto yy10;
		goto yy2;
	}
yy8:	yych = *++YYCURSOR;
	goto yy9;
yy9:
#line 16 "repeater.re"
{RET(1);}
#line 79 "repeater.c"
yy10:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych != '\n')	goto yy2;
		goto yy11;
	} else {
		if(yych <= 'A')	goto yy13;
		if(yych == 'a')	goto yy13;
		goto yy2;
	}
yy11:	yych = *++YYCURSOR;
	goto yy12;
yy12:
#line 17 "repeater.re"
{RET(2);}
#line 94 "repeater.c"
yy13:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych == '\n')	goto yy15;
		goto yy2;
	} else {
		if(yych <= 'A')	goto yy14;
		if(yych != 'a')	goto yy2;
		goto yy14;
	}
yy14:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych != '\n')	goto yy2;
		goto yy15;
	} else {
		if(yych <= 'A')	goto yy17;
		if(yych == 'a')	goto yy17;
		goto yy2;
	}
yy15:	yych = *++YYCURSOR;
	goto yy16;
yy16:
#line 18 "repeater.re"
{RET(3);}
#line 118 "repeater.c"
yy17:	yych = *++YYCURSOR;
	if(yych == '\n')	goto yy20;
	goto yy19;
yy18:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy19;
yy19:	if(yych <= '@'){
		if(yych == '\n')	goto yy15;
		goto yy2;
	} else {
		if(yych <= 'A')	goto yy18;
		if(yych == 'a')	goto yy18;
		goto yy2;
	}
yy20:	yych = *++YYCURSOR;
	goto yy16;
}
#line 21 "repeater.re"

}

#define do_scan(str) scan(str, strlen(str))

main()
{
	do_scan("a\n");
	do_scan("aa\n");
	do_scan("aaa\n");
	do_scan("aaaa\n");
	do_scan("A\n");
	do_scan("AA\n");
	do_scan("aAa\n");
	do_scan("AaaA\n");
	do_scan("Q");
	do_scan("AaaAa\n");
	do_scan("AaaAaA\n");
	do_scan("A");
	do_scan("\n");
	do_scan("0");
}
