/* Generated by re2c 0.9.1-C on Fri Oct  7 22:39:00 2022
 */
#line 1 "sample.re"

#line 5 "sample.c"
{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy0;
	++YYCURSOR;
yy0:
	if((YYLIMIT - YYCURSOR) < 6) YYFILL(6);
	yych = *YYCURSOR;
	if(yych <= '`'){
		if(yych <= '/')	goto yy8;
		if(yych <= '0')	goto yy5;
		if(yych <= '9')	goto yy7;
		goto yy8;
	} else {
		if(yych == 'p')	goto yy2;
		if(yych <= 'z')	goto yy4;
		goto yy8;
	}
yy2:	yych = *++YYCURSOR;
	if(yych == 'r')	goto yy19;
	goto yy18;
yy3:
#line 3 "sample.re"
{return ID;}
#line 30 "sample.c"
yy4:	yych = *++YYCURSOR;
	goto yy18;
yy5:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'x')	goto yy12;
	goto yy11;
yy6:
#line 4 "sample.re"
{return DEC;}
#line 40 "sample.c"
yy7:	yych = *++YYCURSOR;
	goto yy11;
yy8:	yych = *++YYCURSOR;
	goto yy9;
yy9:
#line 6 "sample.re"
{return ERR;}
#line 48 "sample.c"
yy10:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy11;
yy11:	if(yych <= '/')	goto yy6;
	if(yych <= '9')	goto yy10;
	goto yy6;
yy12:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy13;
	if(yych <= '9')	goto yy14;
	if(yych <= '`')	goto yy13;
	if(yych <= 'f')	goto yy14;
	goto yy13;
yy13:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy6;
	}
yy14:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy15;
yy15:	if(yych <= '/')	goto yy16;
	if(yych <= '9')	goto yy14;
	if(yych <= '`')	goto yy16;
	if(yych <= 'f')	goto yy14;
	goto yy16;
yy16:
#line 5 "sample.re"
{return HEX;}
#line 78 "sample.c"
yy17:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy18;
yy18:	if(yych <= '`')	goto yy3;
	if(yych <= 'z')	goto yy17;
	goto yy3;
yy19:	yych = *++YYCURSOR;
	if(yych != 'i')	goto yy18;
	goto yy20;
yy20:	yych = *++YYCURSOR;
	if(yych != 'n')	goto yy18;
	goto yy21;
yy21:	yych = *++YYCURSOR;
	if(yych != 't')	goto yy18;
	goto yy22;
yy22:	yych = *++YYCURSOR;
	if(yych <= '`')	goto yy23;
	if(yych <= 'z')	goto yy17;
	goto yy23;
yy23:
#line 2 "sample.re"
{return PRINT;}
#line 102 "sample.c"
}
#line 7 "sample.re"

