/* Generated by re2c 0.9.1-C on Fri Oct  7 22:34:11 2022
 */
#line 1 "modula.re"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

typedef unsigned int uint;
typedef unsigned char uchar;

#define	BSIZE	8192

#define	YYCTYPE		uchar
#define	YYCURSOR	cursor
#define	YYLIMIT		s->lim
#define	YYMARKER	s->ptr
#define	YYFILL		{cursor = fill(s, cursor);}

#define	RETURN(i)	{s->cur = cursor; return i;}

typedef struct Scanner {
    int			fd;
    uchar		*bot, *tok, *ptr, *cur, *pos, *lim, *top, *eof;
    uint		line;
} Scanner;

uchar *fill(Scanner *s, uchar *cursor){
    if(!s->eof){
	uint cnt = s->tok - s->bot;
	if(cnt){
	    memcpy(s->bot, s->tok, s->lim - s->tok);
	    s->tok = s->bot;
	    s->ptr -= cnt;
	    cursor -= cnt;
	    s->pos -= cnt;
	    s->lim -= cnt;
	}
	if((s->top - s->lim) < BSIZE){
	    uchar *buf = (uchar*) malloc(((s->lim - s->bot) + BSIZE)*sizeof(uchar));
	    memcpy(buf, s->tok, s->lim - s->tok);
	    s->tok = buf;
	    s->ptr = &buf[s->ptr - s->bot];
	    cursor = &buf[cursor - s->bot];
	    s->pos = &buf[s->pos - s->bot];
	    s->lim = &buf[s->lim - s->bot];
	    s->top = &s->lim[BSIZE];
	    free(s->bot);
	    s->bot = buf;
	}
	if((cnt = read(s->fd, (char*) s->lim, BSIZE)) != BSIZE){
	    s->eof = &s->lim[cnt]; *(s->eof)++ = '\n';
	}
	s->lim += cnt;
    }
    return cursor;
}

int scan(Scanner *s){
	uchar *cursor = s->cur;
	uint depth;
std:
	s->tok = cursor;
#line 64 "modula.re"



#line 67 "modula.c"
{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy0;
	++YYCURSOR;
yy0:
	if((YYLIMIT - YYCURSOR) < 15) YYFILL(15);
	yych = *YYCURSOR;
	switch(yych){
	case '\t':	case ' ':	goto yy73;
	case '\n':	goto yy75;
	case '"':	goto yy9;
	case '#':	goto yy10;
	case '&':	goto yy12;
	case '\'':	goto yy7;
	case '(':	goto yy2;
	case ')':	goto yy14;
	case '*':	goto yy16;
	case '+':	goto yy18;
	case ',':	goto yy20;
	case '-':	goto yy22;
	case '.':	goto yy24;
	case '/':	goto yy26;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy4;
	case '8':
	case '9':	goto yy6;
	case ':':	goto yy28;
	case ';':	goto yy30;
	case '<':	goto yy32;
	case '=':	goto yy34;
	case '>':	goto yy36;
	case 'A':	goto yy52;
	case 'B':	goto yy54;
	case 'C':	goto yy55;
	case 'D':	goto yy56;
	case 'E':	goto yy57;
	case 'F':	goto yy58;
	case 'G':
	case 'H':	case 'J':
	case 'K':	case 'X':
	case 'Y':
	case 'Z':	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy72;
	case 'I':	goto yy59;
	case 'L':	goto yy60;
	case 'M':	goto yy61;
	case 'N':	goto yy62;
	case 'O':	goto yy63;
	case 'P':	goto yy64;
	case 'Q':	goto yy65;
	case 'R':	goto yy66;
	case 'S':	goto yy67;
	case 'T':	goto yy68;
	case 'U':	goto yy69;
	case 'V':	goto yy70;
	case 'W':	goto yy71;
	case '[':	goto yy38;
	case ']':	goto yy40;
	case '^':	goto yy42;
	case '{':	goto yy44;
	case '|':	goto yy46;
	case '}':	goto yy48;
	case '~':	goto yy50;
	default:	goto yy77;
	}
yy2:	yych = *++YYCURSOR;
	if(yych == '*')	goto yy297;
	goto yy3;
yy3:
#line 79 "modula.re"
{RETURN(9);}
#line 170 "modula.c"
yy4:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy292;
yy5:
#line 69 "modula.re"
{RETURN(1);}
#line 177 "modula.c"
yy6:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy278;
yy7:	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych != '\n')	goto yy274;
	goto yy8;
yy8:
#line 158 "modula.re"
{
		printf("unexpected character: %c\n", *s->tok);
		goto std;
	    }
#line 191 "modula.c"
yy9:	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '\n')	goto yy8;
	goto yy269;
yy10:	yych = *++YYCURSOR;
	goto yy11;
yy11:
#line 77 "modula.re"
{RETURN(7);}
#line 201 "modula.c"
yy12:	yych = *++YYCURSOR;
	goto yy13;
yy13:
#line 78 "modula.re"
{RETURN(8);}
#line 207 "modula.c"
yy14:	yych = *++YYCURSOR;
	goto yy15;
yy15:
#line 80 "modula.re"
{RETURN(10);}
#line 213 "modula.c"
yy16:	yych = *++YYCURSOR;
	goto yy17;
yy17:
#line 81 "modula.re"
{RETURN(11);}
#line 219 "modula.c"
yy18:	yych = *++YYCURSOR;
	goto yy19;
yy19:
#line 82 "modula.re"
{RETURN(12);}
#line 225 "modula.c"
yy20:	yych = *++YYCURSOR;
	goto yy21;
yy21:
#line 83 "modula.re"
{RETURN(13);}
#line 231 "modula.c"
yy22:	yych = *++YYCURSOR;
	goto yy23;
yy23:
#line 84 "modula.re"
{RETURN(14);}
#line 237 "modula.c"
yy24:	yych = *++YYCURSOR;
	if(yych == '.')	goto yy266;
	goto yy25;
yy25:
#line 85 "modula.re"
{RETURN(15);}
#line 244 "modula.c"
yy26:	yych = *++YYCURSOR;
	goto yy27;
yy27:
#line 87 "modula.re"
{RETURN(17);}
#line 250 "modula.c"
yy28:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy264;
	goto yy29;
yy29:
#line 88 "modula.re"
{RETURN(18);}
#line 257 "modula.c"
yy30:	yych = *++YYCURSOR;
	goto yy31;
yy31:
#line 90 "modula.re"
{RETURN(20);}
#line 263 "modula.c"
yy32:	yych = *++YYCURSOR;
	if(yych <= '<')	goto yy33;
	if(yych <= '=')	goto yy262;
	if(yych <= '>')	goto yy260;
	goto yy33;
yy33:
#line 91 "modula.re"
{RETURN(21);}
#line 272 "modula.c"
yy34:	yych = *++YYCURSOR;
	goto yy35;
yy35:
#line 94 "modula.re"
{RETURN(24);}
#line 278 "modula.c"
yy36:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy258;
	goto yy37;
yy37:
#line 95 "modula.re"
{RETURN(25);}
#line 285 "modula.c"
yy38:	yych = *++YYCURSOR;
	goto yy39;
yy39:
#line 97 "modula.re"
{RETURN(27);}
#line 291 "modula.c"
yy40:	yych = *++YYCURSOR;
	goto yy41;
yy41:
#line 98 "modula.re"
{RETURN(28);}
#line 297 "modula.c"
yy42:	yych = *++YYCURSOR;
	goto yy43;
yy43:
#line 99 "modula.re"
{RETURN(29);}
#line 303 "modula.c"
yy44:	yych = *++YYCURSOR;
	goto yy45;
yy45:
#line 100 "modula.re"
{RETURN(30);}
#line 309 "modula.c"
yy46:	yych = *++YYCURSOR;
	goto yy47;
yy47:
#line 101 "modula.re"
{RETURN(31);}
#line 315 "modula.c"
yy48:	yych = *++YYCURSOR;
	goto yy49;
yy49:
#line 102 "modula.re"
{RETURN(32);}
#line 321 "modula.c"
yy50:	yych = *++YYCURSOR;
	goto yy51;
yy51:
#line 103 "modula.re"
{RETURN(33);}
#line 327 "modula.c"
yy52:	yych = *++YYCURSOR;
	if(yych == 'N')	goto yy250;
	if(yych == 'R')	goto yy251;
	goto yy81;
yy53:
#line 146 "modula.re"
{RETURN(74);}
#line 335 "modula.c"
yy54:	yych = *++YYCURSOR;
	if(yych == 'E')	goto yy243;
	if(yych == 'Y')	goto yy244;
	goto yy81;
yy55:	yych = *++YYCURSOR;
	if(yych == 'A')	goto yy234;
	if(yych == 'O')	goto yy235;
	goto yy81;
yy56:	yych = *++YYCURSOR;
	if(yych <= 'H'){
		if(yych == 'E')	goto yy219;
		goto yy81;
	} else {
		if(yych <= 'I')	goto yy220;
		if(yych == 'O')	goto yy221;
		goto yy81;
	}
yy57:	yych = *++YYCURSOR;
	if(yych <= 'M'){
		if(yych == 'L')	goto yy200;
		goto yy81;
	} else {
		if(yych <= 'N')	goto yy201;
		if(yych == 'X')	goto yy202;
		goto yy81;
	}
yy58:	yych = *++YYCURSOR;
	if(yych == 'O')	goto yy193;
	if(yych == 'R')	goto yy194;
	goto yy81;
yy59:	yych = *++YYCURSOR;
	if(yych <= 'L'){
		if(yych == 'F')	goto yy171;
		goto yy81;
	} else {
		if(yych <= 'M')	goto yy173;
		if(yych <= 'N')	goto yy174;
		goto yy81;
	}
yy60:	yych = *++YYCURSOR;
	if(yych == 'O')	goto yy167;
	goto yy81;
yy61:	yych = *++YYCURSOR;
	if(yych == 'O')	goto yy160;
	goto yy81;
yy62:	yych = *++YYCURSOR;
	if(yych == 'O')	goto yy157;
	goto yy81;
yy63:	yych = *++YYCURSOR;
	if(yych == 'F')	goto yy153;
	if(yych == 'R')	goto yy155;
	goto yy81;
yy64:	yych = *++YYCURSOR;
	if(yych == 'O')	goto yy137;
	if(yych == 'R')	goto yy138;
	goto yy81;
yy65:	yych = *++YYCURSOR;
	if(yych == 'U')	goto yy128;
	goto yy81;
yy66:	yych = *++YYCURSOR;
	if(yych == 'E')	goto yy112;
	goto yy81;
yy67:	yych = *++YYCURSOR;
	if(yych == 'E')	goto yy109;
	goto yy81;
yy68:	yych = *++YYCURSOR;
	if(yych <= 'N'){
		if(yych == 'H')	goto yy99;
		goto yy81;
	} else {
		if(yych <= 'O')	goto yy100;
		if(yych == 'Y')	goto yy102;
		goto yy81;
	}
yy69:	yych = *++YYCURSOR;
	if(yych == 'N')	goto yy94;
	goto yy81;
yy70:	yych = *++YYCURSOR;
	if(yych == 'A')	goto yy91;
	goto yy81;
yy71:	yych = *++YYCURSOR;
	if(yych <= 'G')	goto yy81;
	if(yych <= 'H')	goto yy82;
	if(yych <= 'I')	goto yy83;
	goto yy81;
yy72:	yych = *++YYCURSOR;
	goto yy81;
yy73:	yych = *++YYCURSOR;
	goto yy79;
yy74:
#line 148 "modula.re"
{ goto std; }
#line 428 "modula.c"
yy75:	yych = *++YYCURSOR;
	goto yy76;
yy76:
#line 151 "modula.re"
{
		if(cursor == s->eof) RETURN(0);
		s->pos = cursor; s->line++;
		goto std;
	    }
#line 438 "modula.c"
yy77:	yych = *++YYCURSOR;
	goto yy8;
yy78:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy79;
yy79:	if(yych == '\t')	goto yy78;
	if(yych == ' ')	goto yy78;
	goto yy74;
yy80:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy81;
yy81:	if(yych <= '@'){
		if(yych <= '/')	goto yy53;
		if(yych <= '9')	goto yy80;
		goto yy53;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy53;
		if(yych <= 'z')	goto yy80;
		goto yy53;
	}
yy82:	yych = *++YYCURSOR;
	if(yych == 'I')	goto yy87;
	goto yy81;
yy83:	yych = *++YYCURSOR;
	if(yych != 'T')	goto yy81;
	goto yy84;
yy84:	yych = *++YYCURSOR;
	if(yych != 'H')	goto yy81;
	goto yy85;
yy85:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy86;
		if(yych <= '9')	goto yy80;
		goto yy86;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy86;
		if(yych <= 'z')	goto yy80;
		goto yy86;
	}
yy86:
#line 144 "modula.re"
{RETURN(73);}
#line 485 "modula.c"
yy87:	yych = *++YYCURSOR;
	if(yych != 'L')	goto yy81;
	goto yy88;
yy88:	yych = *++YYCURSOR;
	if(yych != 'E')	goto yy81;
	goto yy89;
yy89:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy90;
		if(yych <= '9')	goto yy80;
		goto yy90;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy90;
		if(yych <= 'z')	goto yy80;
		goto yy90;
	}
yy90:
#line 143 "modula.re"
{RETURN(72);}
#line 506 "modula.c"
yy91:	yych = *++YYCURSOR;
	if(yych != 'R')	goto yy81;
	goto yy92;
yy92:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy93;
		if(yych <= '9')	goto yy80;
		goto yy93;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy93;
		if(yych <= 'z')	goto yy80;
		goto yy93;
	}
yy93:
#line 142 "modula.re"
{RETURN(71);}
#line 524 "modula.c"
yy94:	yych = *++YYCURSOR;
	if(yych != 'T')	goto yy81;
	goto yy95;
yy95:	yych = *++YYCURSOR;
	if(yych != 'I')	goto yy81;
	goto yy96;
yy96:	yych = *++YYCURSOR;
	if(yych != 'L')	goto yy81;
	goto yy97;
yy97:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy98;
		if(yych <= '9')	goto yy80;
		goto yy98;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy98;
		if(yych <= 'z')	goto yy80;
		goto yy98;
	}
yy98:
#line 141 "modula.re"
{RETURN(70);}
#line 548 "modula.c"
yy99:	yych = *++YYCURSOR;
	if(yych == 'E')	goto yy106;
	goto yy81;
yy100:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy101;
		if(yych <= '9')	goto yy80;
		goto yy101;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy101;
		if(yych <= 'z')	goto yy80;
		goto yy101;
	}
yy101:
#line 139 "modula.re"
{RETURN(68);}
#line 566 "modula.c"
yy102:	yych = *++YYCURSOR;
	if(yych != 'P')	goto yy81;
	goto yy103;
yy103:	yych = *++YYCURSOR;
	if(yych != 'E')	goto yy81;
	goto yy104;
yy104:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy105;
		if(yych <= '9')	goto yy80;
		goto yy105;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy105;
		if(yych <= 'z')	goto yy80;
		goto yy105;
	}
yy105:
#line 140 "modula.re"
{RETURN(69);}
#line 587 "modula.c"
yy106:	yych = *++YYCURSOR;
	if(yych != 'N')	goto yy81;
	goto yy107;
yy107:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy108;
		if(yych <= '9')	goto yy80;
		goto yy108;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy108;
		if(yych <= 'z')	goto yy80;
		goto yy108;
	}
yy108:
#line 138 "modula.re"
{RETURN(67);}
#line 605 "modula.c"
yy109:	yych = *++YYCURSOR;
	if(yych != 'T')	goto yy81;
	goto yy110;
yy110:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy111;
		if(yych <= '9')	goto yy80;
		goto yy111;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy111;
		if(yych <= 'z')	goto yy80;
		goto yy111;
	}
yy111:
#line 137 "modula.re"
{RETURN(66);}
#line 623 "modula.c"
yy112:	yych = *++YYCURSOR;
	if(yych <= 'O'){
		if(yych != 'C')	goto yy81;
		goto yy113;
	} else {
		if(yych <= 'P')	goto yy114;
		if(yych == 'T')	goto yy115;
		goto yy81;
	}
yy113:	yych = *++YYCURSOR;
	if(yych == 'O')	goto yy124;
	goto yy81;
yy114:	yych = *++YYCURSOR;
	if(yych == 'E')	goto yy120;
	goto yy81;
yy115:	yych = *++YYCURSOR;
	if(yych != 'U')	goto yy81;
	goto yy116;
yy116:	yych = *++YYCURSOR;
	if(yych != 'R')	goto yy81;
	goto yy117;
yy117:	yych = *++YYCURSOR;
	if(yych != 'N')	goto yy81;
	goto yy118;
yy118:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy119;
		if(yych <= '9')	goto yy80;
		goto yy119;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy119;
		if(yych <= 'z')	goto yy80;
		goto yy119;
	}
yy119:
#line 136 "modula.re"
{RETURN(65);}
#line 662 "modula.c"
yy120:	yych = *++YYCURSOR;
	if(yych != 'A')	goto yy81;
	goto yy121;
yy121:	yych = *++YYCURSOR;
	if(yych != 'T')	goto yy81;
	goto yy122;
yy122:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy123;
		if(yych <= '9')	goto yy80;
		goto yy123;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy123;
		if(yych <= 'z')	goto yy80;
		goto yy123;
	}
yy123:
#line 135 "modula.re"
{RETURN(64);}
#line 683 "modula.c"
yy124:	yych = *++YYCURSOR;
	if(yych != 'R')	goto yy81;
	goto yy125;
yy125:	yych = *++YYCURSOR;
	if(yych != 'D')	goto yy81;
	goto yy126;
yy126:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy127;
		if(yych <= '9')	goto yy80;
		goto yy127;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy127;
		if(yych <= 'z')	goto yy80;
		goto yy127;
	}
yy127:
#line 134 "modula.re"
{RETURN(63);}
#line 704 "modula.c"
yy128:	yych = *++YYCURSOR;
	if(yych != 'A')	goto yy81;
	goto yy129;
yy129:	yych = *++YYCURSOR;
	if(yych != 'L')	goto yy81;
	goto yy130;
yy130:	yych = *++YYCURSOR;
	if(yych != 'I')	goto yy81;
	goto yy131;
yy131:	yych = *++YYCURSOR;
	if(yych != 'F')	goto yy81;
	goto yy132;
yy132:	yych = *++YYCURSOR;
	if(yych != 'I')	goto yy81;
	goto yy133;
yy133:	yych = *++YYCURSOR;
	if(yych != 'E')	goto yy81;
	goto yy134;
yy134:	yych = *++YYCURSOR;
	if(yych != 'D')	goto yy81;
	goto yy135;
yy135:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy136;
		if(yych <= '9')	goto yy80;
		goto yy136;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy136;
		if(yych <= 'z')	goto yy80;
		goto yy136;
	}
yy136:
#line 133 "modula.re"
{RETURN(62);}
#line 740 "modula.c"
yy137:	yych = *++YYCURSOR;
	if(yych == 'I')	goto yy147;
	goto yy81;
yy138:	yych = *++YYCURSOR;
	if(yych != 'O')	goto yy81;
	goto yy139;
yy139:	yych = *++YYCURSOR;
	if(yych != 'C')	goto yy81;
	goto yy140;
yy140:	yych = *++YYCURSOR;
	if(yych != 'E')	goto yy81;
	goto yy141;
yy141:	yych = *++YYCURSOR;
	if(yych != 'D')	goto yy81;
	goto yy142;
yy142:	yych = *++YYCURSOR;
	if(yych != 'U')	goto yy81;
	goto yy143;
yy143:	yych = *++YYCURSOR;
	if(yych != 'R')	goto yy81;
	goto yy144;
yy144:	yych = *++YYCURSOR;
	if(yych != 'E')	goto yy81;
	goto yy145;
yy145:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy146;
		if(yych <= '9')	goto yy80;
		goto yy146;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy146;
		if(yych <= 'z')	goto yy80;
		goto yy146;
	}
yy146:
#line 132 "modula.re"
{RETURN(61);}
#line 779 "modula.c"
yy147:	yych = *++YYCURSOR;
	if(yych != 'N')	goto yy81;
	goto yy148;
yy148:	yych = *++YYCURSOR;
	if(yych != 'T')	goto yy81;
	goto yy149;
yy149:	yych = *++YYCURSOR;
	if(yych != 'E')	goto yy81;
	goto yy150;
yy150:	yych = *++YYCURSOR;
	if(yych != 'R')	goto yy81;
	goto yy151;
yy151:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy152;
		if(yych <= '9')	goto yy80;
		goto yy152;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy152;
		if(yych <= 'z')	goto yy80;
		goto yy152;
	}
yy152:
#line 131 "modula.re"
{RETURN(60);}
#line 806 "modula.c"
yy153:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy154;
		if(yych <= '9')	goto yy80;
		goto yy154;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy154;
		if(yych <= 'z')	goto yy80;
		goto yy154;
	}
yy154:
#line 129 "modula.re"
{RETURN(58);}
#line 821 "modula.c"
yy155:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy156;
		if(yych <= '9')	goto yy80;
		goto yy156;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy156;
		if(yych <= 'z')	goto yy80;
		goto yy156;
	}
yy156:
#line 130 "modula.re"
{RETURN(59);}
#line 836 "modula.c"
yy157:	yych = *++YYCURSOR;
	if(yych != 'T')	goto yy81;
	goto yy158;
yy158:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy159;
		if(yych <= '9')	goto yy80;
		goto yy159;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy159;
		if(yych <= 'z')	goto yy80;
		goto yy159;
	}
yy159:
#line 128 "modula.re"
{RETURN(57);}
#line 854 "modula.c"
yy160:	yych = *++YYCURSOR;
	if(yych != 'D')	goto yy81;
	goto yy161;
yy161:	yych = *++YYCURSOR;
	if(yych <= 'T'){
		if(yych <= '/')	goto yy162;
		if(yych <= '9')	goto yy80;
		if(yych >= 'A')	goto yy80;
		goto yy162;
	} else {
		if(yych <= 'Z'){
			if(yych <= 'U')	goto yy163;
			goto yy80;
		} else {
			if(yych <= '`')	goto yy162;
			if(yych <= 'z')	goto yy80;
			goto yy162;
		}
	}
yy162:
#line 126 "modula.re"
{RETURN(55);}
#line 877 "modula.c"
yy163:	yych = *++YYCURSOR;
	if(yych != 'L')	goto yy81;
	goto yy164;
yy164:	yych = *++YYCURSOR;
	if(yych != 'E')	goto yy81;
	goto yy165;
yy165:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy166;
		if(yych <= '9')	goto yy80;
		goto yy166;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy166;
		if(yych <= 'z')	goto yy80;
		goto yy166;
	}
yy166:
#line 127 "modula.re"
{RETURN(56);}
#line 898 "modula.c"
yy167:	yych = *++YYCURSOR;
	if(yych != 'O')	goto yy81;
	goto yy168;
yy168:	yych = *++YYCURSOR;
	if(yych != 'P')	goto yy81;
	goto yy169;
yy169:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy170;
		if(yych <= '9')	goto yy80;
		goto yy170;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy170;
		if(yych <= 'z')	goto yy80;
		goto yy170;
	}
yy170:
#line 125 "modula.re"
{RETURN(54);}
#line 919 "modula.c"
yy171:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy172;
		if(yych <= '9')	goto yy80;
		goto yy172;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy172;
		if(yych <= 'z')	goto yy80;
		goto yy172;
	}
yy172:
#line 121 "modula.re"
{RETURN(50);}
#line 934 "modula.c"
yy173:	yych = *++YYCURSOR;
	if(yych == 'P')	goto yy176;
	goto yy81;
yy174:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy175;
		if(yych <= '9')	goto yy80;
		goto yy175;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy175;
		if(yych <= 'z')	goto yy80;
		goto yy175;
	}
yy175:
#line 124 "modula.re"
{RETURN(53);}
#line 952 "modula.c"
yy176:	yych = *++YYCURSOR;
	if(yych == 'L')	goto yy177;
	if(yych == 'O')	goto yy178;
	goto yy81;
yy177:	yych = *++YYCURSOR;
	if(yych == 'E')	goto yy182;
	goto yy81;
yy178:	yych = *++YYCURSOR;
	if(yych != 'R')	goto yy81;
	goto yy179;
yy179:	yych = *++YYCURSOR;
	if(yych != 'T')	goto yy81;
	goto yy180;
yy180:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy181;
		if(yych <= '9')	goto yy80;
		goto yy181;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy181;
		if(yych <= 'z')	goto yy80;
		goto yy181;
	}
yy181:
#line 123 "modula.re"
{RETURN(52);}
#line 980 "modula.c"
yy182:	yych = *++YYCURSOR;
	if(yych != 'M')	goto yy81;
	goto yy183;
yy183:	yych = *++YYCURSOR;
	if(yych != 'E')	goto yy81;
	goto yy184;
yy184:	yych = *++YYCURSOR;
	if(yych != 'N')	goto yy81;
	goto yy185;
yy185:	yych = *++YYCURSOR;
	if(yych != 'T')	goto yy81;
	goto yy186;
yy186:	yych = *++YYCURSOR;
	if(yych != 'A')	goto yy81;
	goto yy187;
yy187:	yych = *++YYCURSOR;
	if(yych != 'T')	goto yy81;
	goto yy188;
yy188:	yych = *++YYCURSOR;
	if(yych != 'I')	goto yy81;
	goto yy189;
yy189:	yych = *++YYCURSOR;
	if(yych != 'O')	goto yy81;
	goto yy190;
yy190:	yych = *++YYCURSOR;
	if(yych != 'N')	goto yy81;
	goto yy191;
yy191:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy192;
		if(yych <= '9')	goto yy80;
		goto yy192;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy192;
		if(yych <= 'z')	goto yy80;
		goto yy192;
	}
yy192:
#line 122 "modula.re"
{RETURN(51);}
#line 1022 "modula.c"
yy193:	yych = *++YYCURSOR;
	if(yych == 'R')	goto yy198;
	goto yy81;
yy194:	yych = *++YYCURSOR;
	if(yych != 'O')	goto yy81;
	goto yy195;
yy195:	yych = *++YYCURSOR;
	if(yych != 'M')	goto yy81;
	goto yy196;
yy196:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy197;
		if(yych <= '9')	goto yy80;
		goto yy197;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy197;
		if(yych <= 'z')	goto yy80;
		goto yy197;
	}
yy197:
#line 120 "modula.re"
{RETURN(49);}
#line 1046 "modula.c"
yy198:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy199;
		if(yych <= '9')	goto yy80;
		goto yy199;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy199;
		if(yych <= 'z')	goto yy80;
		goto yy199;
	}
yy199:
#line 119 "modula.re"
{RETURN(48);}
#line 1061 "modula.c"
yy200:	yych = *++YYCURSOR;
	if(yych == 'S')	goto yy213;
	goto yy81;
yy201:	yych = *++YYCURSOR;
	if(yych == 'D')	goto yy211;
	goto yy81;
yy202:	yych = *++YYCURSOR;
	if(yych == 'I')	goto yy203;
	if(yych == 'P')	goto yy204;
	goto yy81;
yy203:	yych = *++YYCURSOR;
	if(yych == 'T')	goto yy209;
	goto yy81;
yy204:	yych = *++YYCURSOR;
	if(yych != 'O')	goto yy81;
	goto yy205;
yy205:	yych = *++YYCURSOR;
	if(yych != 'R')	goto yy81;
	goto yy206;
yy206:	yych = *++YYCURSOR;
	if(yych != 'T')	goto yy81;
	goto yy207;
yy207:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy208;
		if(yych <= '9')	goto yy80;
		goto yy208;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy208;
		if(yych <= 'z')	goto yy80;
		goto yy208;
	}
yy208:
#line 118 "modula.re"
{RETURN(47);}
#line 1098 "modula.c"
yy209:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy210;
		if(yych <= '9')	goto yy80;
		goto yy210;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy210;
		if(yych <= 'z')	goto yy80;
		goto yy210;
	}
yy210:
#line 117 "modula.re"
{RETURN(46);}
#line 1113 "modula.c"
yy211:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy212;
		if(yych <= '9')	goto yy80;
		goto yy212;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy212;
		if(yych <= 'z')	goto yy80;
		goto yy212;
	}
yy212:
#line 116 "modula.re"
{RETURN(45);}
#line 1128 "modula.c"
yy213:	yych = *++YYCURSOR;
	if(yych == 'E')	goto yy214;
	if(yych == 'I')	goto yy216;
	goto yy81;
yy214:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy215;
		if(yych <= '9')	goto yy80;
		goto yy215;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy215;
		if(yych <= 'z')	goto yy80;
		goto yy215;
	}
yy215:
#line 114 "modula.re"
{RETURN(43);}
#line 1147 "modula.c"
yy216:	yych = *++YYCURSOR;
	if(yych != 'F')	goto yy81;
	goto yy217;
yy217:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy218;
		if(yych <= '9')	goto yy80;
		goto yy218;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy218;
		if(yych <= 'z')	goto yy80;
		goto yy218;
	}
yy218:
#line 115 "modula.re"
{RETURN(44);}
#line 1165 "modula.c"
yy219:	yych = *++YYCURSOR;
	if(yych == 'F')	goto yy225;
	goto yy81;
yy220:	yych = *++YYCURSOR;
	if(yych == 'V')	goto yy223;
	goto yy81;
yy221:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy222;
		if(yych <= '9')	goto yy80;
		goto yy222;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy222;
		if(yych <= 'z')	goto yy80;
		goto yy222;
	}
yy222:
#line 113 "modula.re"
{RETURN(42);}
#line 1186 "modula.c"
yy223:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy224;
		if(yych <= '9')	goto yy80;
		goto yy224;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy224;
		if(yych <= 'z')	goto yy80;
		goto yy224;
	}
yy224:
#line 112 "modula.re"
{RETURN(41);}
#line 1201 "modula.c"
yy225:	yych = *++YYCURSOR;
	if(yych != 'I')	goto yy81;
	goto yy226;
yy226:	yych = *++YYCURSOR;
	if(yych != 'N')	goto yy81;
	goto yy227;
yy227:	yych = *++YYCURSOR;
	if(yych != 'I')	goto yy81;
	goto yy228;
yy228:	yych = *++YYCURSOR;
	if(yych != 'T')	goto yy81;
	goto yy229;
yy229:	yych = *++YYCURSOR;
	if(yych != 'I')	goto yy81;
	goto yy230;
yy230:	yych = *++YYCURSOR;
	if(yych != 'O')	goto yy81;
	goto yy231;
yy231:	yych = *++YYCURSOR;
	if(yych != 'N')	goto yy81;
	goto yy232;
yy232:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy233;
		if(yych <= '9')	goto yy80;
		goto yy233;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy233;
		if(yych <= 'z')	goto yy80;
		goto yy233;
	}
yy233:
#line 111 "modula.re"
{RETURN(40);}
#line 1237 "modula.c"
yy234:	yych = *++YYCURSOR;
	if(yych == 'S')	goto yy240;
	goto yy81;
yy235:	yych = *++YYCURSOR;
	if(yych != 'N')	goto yy81;
	goto yy236;
yy236:	yych = *++YYCURSOR;
	if(yych != 'S')	goto yy81;
	goto yy237;
yy237:	yych = *++YYCURSOR;
	if(yych != 'T')	goto yy81;
	goto yy238;
yy238:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy239;
		if(yych <= '9')	goto yy80;
		goto yy239;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy239;
		if(yych <= 'z')	goto yy80;
		goto yy239;
	}
yy239:
#line 110 "modula.re"
{RETURN(39);}
#line 1264 "modula.c"
yy240:	yych = *++YYCURSOR;
	if(yych != 'E')	goto yy81;
	goto yy241;
yy241:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy242;
		if(yych <= '9')	goto yy80;
		goto yy242;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy242;
		if(yych <= 'z')	goto yy80;
		goto yy242;
	}
yy242:
#line 109 "modula.re"
{RETURN(38);}
#line 1282 "modula.c"
yy243:	yych = *++YYCURSOR;
	if(yych == 'G')	goto yy246;
	goto yy81;
yy244:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy245;
		if(yych <= '9')	goto yy80;
		goto yy245;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy245;
		if(yych <= 'z')	goto yy80;
		goto yy245;
	}
yy245:
#line 108 "modula.re"
{RETURN(37);}
#line 1300 "modula.c"
yy246:	yych = *++YYCURSOR;
	if(yych != 'I')	goto yy81;
	goto yy247;
yy247:	yych = *++YYCURSOR;
	if(yych != 'N')	goto yy81;
	goto yy248;
yy248:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy249;
		if(yych <= '9')	goto yy80;
		goto yy249;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy249;
		if(yych <= 'z')	goto yy80;
		goto yy249;
	}
yy249:
#line 107 "modula.re"
{RETURN(36);}
#line 1321 "modula.c"
yy250:	yych = *++YYCURSOR;
	if(yych == 'D')	goto yy256;
	goto yy81;
yy251:	yych = *++YYCURSOR;
	if(yych != 'R')	goto yy81;
	goto yy252;
yy252:	yych = *++YYCURSOR;
	if(yych != 'A')	goto yy81;
	goto yy253;
yy253:	yych = *++YYCURSOR;
	if(yych != 'Y')	goto yy81;
	goto yy254;
yy254:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy255;
		if(yych <= '9')	goto yy80;
		goto yy255;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy255;
		if(yych <= 'z')	goto yy80;
		goto yy255;
	}
yy255:
#line 106 "modula.re"
{RETURN(35);}
#line 1348 "modula.c"
yy256:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy257;
		if(yych <= '9')	goto yy80;
		goto yy257;
	} else {
		if(yych <= 'Z')	goto yy80;
		if(yych <= '`')	goto yy257;
		if(yych <= 'z')	goto yy80;
		goto yy257;
	}
yy257:
#line 105 "modula.re"
{RETURN(34);}
#line 1363 "modula.c"
yy258:	yych = *++YYCURSOR;
	goto yy259;
yy259:
#line 96 "modula.re"
{RETURN(26);}
#line 1369 "modula.c"
yy260:	yych = *++YYCURSOR;
	goto yy261;
yy261:
#line 93 "modula.re"
{RETURN(23);}
#line 1375 "modula.c"
yy262:	yych = *++YYCURSOR;
	goto yy263;
yy263:
#line 92 "modula.re"
{RETURN(22);}
#line 1381 "modula.c"
yy264:	yych = *++YYCURSOR;
	goto yy265;
yy265:
#line 89 "modula.re"
{RETURN(19);}
#line 1387 "modula.c"
yy266:	yych = *++YYCURSOR;
	goto yy267;
yy267:
#line 86 "modula.re"
{RETURN(16);}
#line 1393 "modula.c"
yy268:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy269;
yy269:	if(yych == '\n')	goto yy270;
	if(yych == '"')	goto yy271;
	goto yy268;
yy270:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy5;
	case 3:	goto yy294;
	case 4:	goto yy296;
	case 2:	goto yy276;
	case 1:	goto yy8;
	}
yy271:	yych = *++YYCURSOR;
	goto yy272;
yy272:
#line 75 "modula.re"
{RETURN(6);}
#line 1414 "modula.c"
yy273:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy274;
yy274:	if(yych == '\n')	goto yy270;
	if(yych == '\'')	goto yy271;
	goto yy273;
yy275:	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '.')	goto yy283;
	goto yy286;
yy276:
#line 74 "modula.re"
{RETURN(5);}
#line 1429 "modula.c"
yy277:	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	goto yy278;
yy278:	if(yych <= '9'){
		if(yych == '.')	goto yy275;
		if(yych <= '/')	goto yy5;
		goto yy277;
	} else {
		if(yych <= 'F'){
			if(yych <= '@')	goto yy5;
			goto yy279;
		} else {
			if(yych == 'H')	goto yy281;
			goto yy5;
		}
	}
yy279:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy280;
yy280:	if(yych <= '@'){
		if(yych <= '/')	goto yy270;
		if(yych <= '9')	goto yy279;
		goto yy270;
	} else {
		if(yych <= 'F')	goto yy279;
		if(yych != 'H')	goto yy270;
		goto yy281;
	}
yy281:	yych = *++YYCURSOR;
	goto yy282;
yy282:
#line 73 "modula.re"
{RETURN(4);}
#line 1466 "modula.c"
yy283:	yych = *++YYCURSOR;
	goto yy284;
yy284:	YYCURSOR -= 2;
#line 70 "modula.re"
{RETURN(1);}
#line 1472 "modula.c"
yy285:	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	goto yy286;
yy286:	if(yych <= '/')	goto yy276;
	if(yych <= '9')	goto yy285;
	if(yych != 'E')	goto yy276;
	goto yy287;
yy287:	yych = *++YYCURSOR;
	if(yych <= ','){
		if(yych != '+')	goto yy270;
		goto yy288;
	} else {
		if(yych <= '-')	goto yy288;
		if(yych <= '/')	goto yy270;
		if(yych <= '9')	goto yy289;
		goto yy270;
	}
yy288:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy270;
	if(yych >= ':')	goto yy270;
	goto yy289;
yy289:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy290;
yy290:	if(yych <= '/')	goto yy276;
	if(yych <= '9')	goto yy289;
	goto yy276;
yy291:	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	goto yy292;
yy292:	switch(yych){
	case '.':	goto yy275;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy291;
	case '8':
	case '9':	goto yy277;
	case 'A':	case 'D':
	case 'E':
	case 'F':	goto yy279;
	case 'B':	goto yy293;
	case 'C':	goto yy295;
	case 'H':	goto yy281;
	default:	goto yy5;
	}
yy293:	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '@'){
		if(yych <= '/')	goto yy294;
		if(yych <= '9')	goto yy279;
		goto yy294;
	} else {
		if(yych <= 'F')	goto yy279;
		if(yych == 'H')	goto yy281;
		goto yy294;
	}
yy294:
#line 71 "modula.re"
{RETURN(2);}
#line 1542 "modula.c"
yy295:	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '@'){
		if(yych <= '/')	goto yy296;
		if(yych <= '9')	goto yy279;
		goto yy296;
	} else {
		if(yych <= 'F')	goto yy279;
		if(yych == 'H')	goto yy281;
		goto yy296;
	}
yy296:
#line 72 "modula.re"
{RETURN(3);}
#line 1557 "modula.c"
yy297:	yych = *++YYCURSOR;
	goto yy298;
yy298:
#line 67 "modula.re"
{ depth = 1; goto comment; }
#line 1563 "modula.c"
}
#line 162 "modula.re"

comment:

#line 1569 "modula.c"
{
	YYCTYPE yych;
	goto yy299;
	++YYCURSOR;
yy299:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '\''){
		if(yych == '\n')	goto yy304;
		goto yy306;
	} else {
		if(yych <= '(')	goto yy303;
		if(yych != '*')	goto yy306;
		goto yy301;
	}
yy301:	yych = *++YYCURSOR;
	if(yych == ')')	goto yy309;
	goto yy302;
yy302:
#line 179 "modula.re"
{ goto comment; }
#line 1591 "modula.c"
yy303:	yych = *++YYCURSOR;
	if(yych == '*')	goto yy307;
	goto yy302;
yy304:	yych = *++YYCURSOR;
	goto yy305;
yy305:
#line 174 "modula.re"
{
		if(cursor == s->eof) RETURN(0);
		s->tok = s->pos = cursor; s->line++;
		goto comment;
	    }
#line 1604 "modula.c"
yy306:	yych = *++YYCURSOR;
	goto yy302;
yy307:	yych = *++YYCURSOR;
	goto yy308;
yy308:
#line 172 "modula.re"
{ ++depth; goto comment; }
#line 1612 "modula.c"
yy309:	yych = *++YYCURSOR;
	goto yy310;
yy310:
#line 166 "modula.re"
{
		if(--depth == 0)
		    goto std;
		else
		    goto comment;
	    }
#line 1623 "modula.c"
}
#line 180 "modula.re"

}

/*
void putStr(FILE *o, char *s, uint l){
    while(l-- > 0)
	putc(*s++, o);
}
*/

main(){
    Scanner in;
    memset((char*) &in, 0, sizeof(in));
    in.fd = 0;
    while(scan(&in)){
/*
	putc('<', stdout);
	putStr(stdout, (char*) in.tok, in.cur - in.tok);
	putc('>', stdout);
	putc('\n', stdout);
*/
    }
}
