/* Generated by re2c 0.9.1-C on Fri Oct  7 22:41:11 2022
 */
#line 1 "simple.re"
#define	NULL		((char*) 0)
char *scan(char *p){
char *q;
#define	YYCTYPE		char
#define	YYCURSOR	p
#define	YYLIMIT		p
#define	YYMARKER	q
#define	YYFILL(n)

#line 13 "simple.c"
{
	YYCTYPE yych;
	goto yy0;
	++YYCURSOR;
yy0:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '/')	goto yy4;
	if(yych >= ':')	goto yy4;
	goto yy2;
yy2:	yych = *++YYCURSOR;
	goto yy7;
yy3:
#line 10 "simple.re"
{return YYCURSOR;}
#line 29 "simple.c"
yy4:	yych = *++YYCURSOR;
	goto yy5;
yy5:
#line 11 "simple.re"
{return NULL;}
#line 35 "simple.c"
yy6:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy7;
yy7:	if(yych <= '/')	goto yy3;
	if(yych <= '9')	goto yy6;
	goto yy3;
}
#line 12 "simple.re"

}
