/* Generated by re2c 0.9.1-C on Fri Oct  7 22:31:37 2022
 */
#line 1 "cnokw.re"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#define	ADDEQ	257
#define	ANDAND	258
#define	ANDEQ	259
#define	ARRAY	260
#define	ASM	261
#define	AUTO	262
#define	BREAK	263
#define	CASE	264
#define	CHAR	265
#define	CONST	266
#define	CONTINUE	267
#define	DECR	268
#define	DEFAULT	269
#define	DEREF	270
#define	DIVEQ	271
#define	DO	272
#define	DOUBLE	273
#define	ELLIPSIS	274
#define	ELSE	275
#define	ENUM	276
#define	EQL	277
#define	EXTERN	278
#define	FCON	279
#define	FLOAT	280
#define	FOR	281
#define	FUNCTION	282
#define	GEQ	283
#define	GOTO	284
#define	ICON	285
#define	ID	286
#define	IF	287
#define	INCR	288
#define	INT	289
#define	LEQ	290
#define	LONG	291
#define	LSHIFT	292
#define	LSHIFTEQ	293
#define	MODEQ	294
#define	MULEQ	295
#define	NEQ	296
#define	OREQ	297
#define	OROR	298
#define	POINTER	299
#define	REGISTER	300
#define	RETURN	301
#define	RSHIFT	302
#define	RSHIFTEQ	303
#define	SCON	304
#define	SHORT	305
#define	SIGNED	306
#define	SIZEOF	307
#define	STATIC	308
#define	STRUCT	309
#define	SUBEQ	310
#define	SWITCH	311
#define	TYPEDEF	312
#define	UNION	313
#define	UNSIGNED	314
#define	VOID	315
#define	VOLATILE	316
#define	WHILE	317
#define	XOREQ	318
#define	EOI	319

typedef unsigned int uint;
typedef unsigned char uchar;

#define	BSIZE	8192

#define	YYCTYPE		uchar
#define	YYCURSOR	cursor
#define	YYLIMIT		s->lim
#define	YYMARKER	s->ptr
#define	YYFILL(n)	{cursor = fill(s, cursor);}

#define	RET(i)	{s->cur = cursor; return i;}

typedef struct Scanner {
    int			fd;
    uchar		*bot, *tok, *ptr, *cur, *pos, *lim, *top, *eof;
    uint		line;
} Scanner;

uchar *fill(Scanner *s, uchar *cursor){
    if(!s->eof){
	uint cnt = s->tok - s->bot;
	if(cnt){
	    memcpy(s->bot, s->tok, s->lim - s->tok);
	    s->tok = s->bot;
	    s->ptr -= cnt;
	    cursor -= cnt;
	    s->pos -= cnt;
	    s->lim -= cnt;
	}
	if((s->top - s->lim) < BSIZE){
	    uchar *buf = (uchar*) malloc(((s->lim - s->bot) + BSIZE)*sizeof(uchar));
	    memcpy(buf, s->tok, s->lim - s->tok);
	    s->tok = buf;
	    s->ptr = &buf[s->ptr - s->bot];
	    cursor = &buf[cursor - s->bot];
	    s->pos = &buf[s->pos - s->bot];
	    s->lim = &buf[s->lim - s->bot];
	    s->top = &s->lim[BSIZE];
	    free(s->bot);
	    s->bot = buf;
	}
	if((cnt = read(s->fd, (char*) s->lim, BSIZE)) != BSIZE){
	    s->eof = &s->lim[cnt]; *(s->eof)++ = '\n';
	}
	s->lim += cnt;
    }
    return cursor;
}

int scan(Scanner *s){
	uchar *cursor = s->cur;
std:
	s->tok = cursor;
#line 133 "cnokw.re"



#line 130 "cnokw.c"
{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy0;
	++YYCURSOR;
yy0:
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	switch(yych){
	case '\t':	case '\v':
	case '\f':	case ' ':	goto yy58;
	case '\n':	goto yy60;
	case '!':	goto yy34;
	case '"':	goto yy13;
	case '%':	goto yy24;
	case '&':	goto yy26;
	case '\'':	goto yy9;
	case '(':	goto yy46;
	case ')':	goto yy48;
	case '*':	goto yy22;
	case '+':	goto yy18;
	case ',':	goto yy42;
	case '-':	goto yy20;
	case '.':	goto yy11;
	case '/':	goto yy2;
	case '0':	goto yy6;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy8;
	case ':':	goto yy44;
	case ';':	goto yy36;
	case '<':	goto yy16;
	case '=':	goto yy32;
	case '>':	goto yy14;
	case '?':	goto yy56;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	case '_':	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy4;
	case '[':	goto yy50;
	case ']':	goto yy52;
	case '^':	goto yy28;
	case '{':	goto yy38;
	case '|':	goto yy30;
	case '}':	goto yy40;
	case '~':	goto yy54;
	default:	goto yy62;
	}
yy2:	yych = *++YYCURSOR;
	if(yych == '*')	goto yy168;
	if(yych == '=')	goto yy166;
	goto yy3;
yy3:
#line 189 "cnokw.re"
{ RET('/'); }
#line 239 "cnokw.c"
yy4:	yych = *++YYCURSOR;
	goto yy165;
yy5:
#line 138 "cnokw.re"
{ RET(ID); }
#line 245 "cnokw.c"
yy6:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= 'X'){
		if(yych <= 'T'){
			if(yych == 'L')	goto yy140;
			goto yy156;
		} else {
			if(yych <= 'U')	goto yy140;
			if(yych <= 'W')	goto yy156;
			goto yy157;
		}
	} else {
		if(yych <= 't'){
			if(yych == 'l')	goto yy140;
			goto yy156;
		} else {
			if(yych <= 'u')	goto yy140;
			if(yych == 'x')	goto yy157;
			goto yy156;
		}
	}
yy7:
#line 142 "cnokw.re"
{ RET(ICON); }
#line 270 "cnokw.c"
yy8:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy138;
yy9:	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych != '\n')	goto yy128;
	goto yy10;
yy10:
#line 208 "cnokw.re"
{
		printf("unexpected character: %c\n", *s->tok);
		goto std;
	    }
#line 284 "cnokw.c"
yy11:	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '.')	goto yy116;
	if(yych <= '/')	goto yy12;
	if(yych <= '9')	goto yy117;
	goto yy12;
yy12:
#line 182 "cnokw.re"
{ RET('.'); }
#line 294 "cnokw.c"
yy13:	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '\n')	goto yy10;
	goto yy106;
yy14:	yych = *++YYCURSOR;
	if(yych <= '<')	goto yy15;
	if(yych <= '=')	goto yy99;
	if(yych <= '>')	goto yy101;
	goto yy15;
yy15:
#line 192 "cnokw.re"
{ RET('>'); }
#line 307 "cnokw.c"
yy16:	yych = *++YYCURSOR;
	if(yych <= ';')	goto yy17;
	if(yych <= '<')	goto yy95;
	if(yych <= '=')	goto yy93;
	goto yy17;
yy17:
#line 191 "cnokw.re"
{ RET('<'); }
#line 316 "cnokw.c"
yy18:	yych = *++YYCURSOR;
	if(yych == '+')	goto yy89;
	if(yych == '=')	goto yy91;
	goto yy19;
yy19:
#line 187 "cnokw.re"
{ RET('+'); }
#line 324 "cnokw.c"
yy20:	yych = *++YYCURSOR;
	if(yych <= '<'){
		if(yych == '-')	goto yy85;
		goto yy21;
	} else {
		if(yych <= '=')	goto yy87;
		if(yych <= '>')	goto yy83;
		goto yy21;
	}
yy21:
#line 186 "cnokw.re"
{ RET('-'); }
#line 337 "cnokw.c"
yy22:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy81;
	goto yy23;
yy23:
#line 188 "cnokw.re"
{ RET('*'); }
#line 344 "cnokw.c"
yy24:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy79;
	goto yy25;
yy25:
#line 190 "cnokw.re"
{ RET('%'); }
#line 351 "cnokw.c"
yy26:	yych = *++YYCURSOR;
	if(yych == '&')	goto yy75;
	if(yych == '=')	goto yy77;
	goto yy27;
yy27:
#line 183 "cnokw.re"
{ RET('&'); }
#line 359 "cnokw.c"
yy28:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy73;
	goto yy29;
yy29:
#line 193 "cnokw.re"
{ RET('^'); }
#line 366 "cnokw.c"
yy30:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy71;
	if(yych == '|')	goto yy69;
	goto yy31;
yy31:
#line 194 "cnokw.re"
{ RET('|'); }
#line 374 "cnokw.c"
yy32:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy67;
	goto yy33;
yy33:
#line 177 "cnokw.re"
{ RET('='); }
#line 381 "cnokw.c"
yy34:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy65;
	goto yy35;
yy35:
#line 184 "cnokw.re"
{ RET('!'); }
#line 388 "cnokw.c"
yy36:	yych = *++YYCURSOR;
	goto yy37;
yy37:
#line 172 "cnokw.re"
{ RET(';'); }
#line 394 "cnokw.c"
yy38:	yych = *++YYCURSOR;
	goto yy39;
yy39:
#line 173 "cnokw.re"
{ RET('{'); }
#line 400 "cnokw.c"
yy40:	yych = *++YYCURSOR;
	goto yy41;
yy41:
#line 174 "cnokw.re"
{ RET('}'); }
#line 406 "cnokw.c"
yy42:	yych = *++YYCURSOR;
	goto yy43;
yy43:
#line 175 "cnokw.re"
{ RET(','); }
#line 412 "cnokw.c"
yy44:	yych = *++YYCURSOR;
	goto yy45;
yy45:
#line 176 "cnokw.re"
{ RET(':'); }
#line 418 "cnokw.c"
yy46:	yych = *++YYCURSOR;
	goto yy47;
yy47:
#line 178 "cnokw.re"
{ RET('('); }
#line 424 "cnokw.c"
yy48:	yych = *++YYCURSOR;
	goto yy49;
yy49:
#line 179 "cnokw.re"
{ RET(')'); }
#line 430 "cnokw.c"
yy50:	yych = *++YYCURSOR;
	goto yy51;
yy51:
#line 180 "cnokw.re"
{ RET('['); }
#line 436 "cnokw.c"
yy52:	yych = *++YYCURSOR;
	goto yy53;
yy53:
#line 181 "cnokw.re"
{ RET(']'); }
#line 442 "cnokw.c"
yy54:	yych = *++YYCURSOR;
	goto yy55;
yy55:
#line 185 "cnokw.re"
{ RET('~'); }
#line 448 "cnokw.c"
yy56:	yych = *++YYCURSOR;
	goto yy57;
yy57:
#line 195 "cnokw.re"
{ RET('?'); }
#line 454 "cnokw.c"
yy58:	yych = *++YYCURSOR;
	goto yy64;
yy59:
#line 198 "cnokw.re"
{ goto std; }
#line 460 "cnokw.c"
yy60:	yych = *++YYCURSOR;
	goto yy61;
yy61:
#line 201 "cnokw.re"
{
		if(cursor == s->eof) RET(EOI);
		s->pos = cursor; s->line++;
		goto std;
	    }
#line 470 "cnokw.c"
yy62:	yych = *++YYCURSOR;
	goto yy10;
yy63:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy64;
yy64:	if(yych <= '\n'){
		if(yych == '\t')	goto yy63;
		goto yy59;
	} else {
		if(yych <= '\f')	goto yy63;
		if(yych == ' ')	goto yy63;
		goto yy59;
	}
yy65:	yych = *++YYCURSOR;
	goto yy66;
yy66:
#line 171 "cnokw.re"
{ RET(NEQ); }
#line 490 "cnokw.c"
yy67:	yych = *++YYCURSOR;
	goto yy68;
yy68:
#line 170 "cnokw.re"
{ RET(EQL); }
#line 496 "cnokw.c"
yy69:	yych = *++YYCURSOR;
	goto yy70;
yy70:
#line 167 "cnokw.re"
{ RET(OROR); }
#line 502 "cnokw.c"
yy71:	yych = *++YYCURSOR;
	goto yy72;
yy72:
#line 160 "cnokw.re"
{ RET(OREQ); }
#line 508 "cnokw.c"
yy73:	yych = *++YYCURSOR;
	goto yy74;
yy74:
#line 159 "cnokw.re"
{ RET(XOREQ); }
#line 514 "cnokw.c"
yy75:	yych = *++YYCURSOR;
	goto yy76;
yy76:
#line 166 "cnokw.re"
{ RET(ANDAND); }
#line 520 "cnokw.c"
yy77:	yych = *++YYCURSOR;
	goto yy78;
yy78:
#line 158 "cnokw.re"
{ RET(ANDEQ); }
#line 526 "cnokw.c"
yy79:	yych = *++YYCURSOR;
	goto yy80;
yy80:
#line 157 "cnokw.re"
{ RET(MODEQ); }
#line 532 "cnokw.c"
yy81:	yych = *++YYCURSOR;
	goto yy82;
yy82:
#line 155 "cnokw.re"
{ RET(MULEQ); }
#line 538 "cnokw.c"
yy83:	yych = *++YYCURSOR;
	goto yy84;
yy84:
#line 165 "cnokw.re"
{ RET(DEREF); }
#line 544 "cnokw.c"
yy85:	yych = *++YYCURSOR;
	goto yy86;
yy86:
#line 164 "cnokw.re"
{ RET(DECR); }
#line 550 "cnokw.c"
yy87:	yych = *++YYCURSOR;
	goto yy88;
yy88:
#line 154 "cnokw.re"
{ RET(SUBEQ); }
#line 556 "cnokw.c"
yy89:	yych = *++YYCURSOR;
	goto yy90;
yy90:
#line 163 "cnokw.re"
{ RET(INCR); }
#line 562 "cnokw.c"
yy91:	yych = *++YYCURSOR;
	goto yy92;
yy92:
#line 153 "cnokw.re"
{ RET(ADDEQ); }
#line 568 "cnokw.c"
yy93:	yych = *++YYCURSOR;
	goto yy94;
yy94:
#line 168 "cnokw.re"
{ RET(LEQ); }
#line 574 "cnokw.c"
yy95:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy97;
	goto yy96;
yy96:
#line 162 "cnokw.re"
{ RET(LSHIFT); }
#line 581 "cnokw.c"
yy97:	yych = *++YYCURSOR;
	goto yy98;
yy98:
#line 152 "cnokw.re"
{ RET(LSHIFTEQ); }
#line 587 "cnokw.c"
yy99:	yych = *++YYCURSOR;
	goto yy100;
yy100:
#line 169 "cnokw.re"
{ RET(GEQ); }
#line 593 "cnokw.c"
yy101:	yych = *++YYCURSOR;
	if(yych == '=')	goto yy103;
	goto yy102;
yy102:
#line 161 "cnokw.re"
{ RET(RSHIFT); }
#line 600 "cnokw.c"
yy103:	yych = *++YYCURSOR;
	goto yy104;
yy104:
#line 151 "cnokw.re"
{ RET(RSHIFTEQ); }
#line 606 "cnokw.c"
yy105:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy106;
yy106:	if(yych <= '!'){
		if(yych != '\n')	goto yy105;
		goto yy107;
	} else {
		if(yych <= '"')	goto yy109;
		if(yych == '\\')	goto yy108;
		goto yy105;
	}
yy107:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy7;
	case 3:	goto yy119;
	case 2:	goto yy12;
	case 1:	goto yy10;
	}
yy108:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'b'){
		if(yych <= '7'){
			if(yych <= '&'){
				if(yych == '"')	goto yy105;
				goto yy107;
			} else {
				if(yych <= '\'')	goto yy105;
				if(yych <= '/')	goto yy107;
				goto yy112;
			}
		} else {
			if(yych <= '['){
				if(yych == '?')	goto yy105;
				goto yy107;
			} else {
				if(yych <= '\\')	goto yy105;
				if(yych <= '`')	goto yy107;
				goto yy105;
			}
		}
	} else {
		if(yych <= 'r'){
			if(yych <= 'm'){
				if(yych == 'f')	goto yy105;
				goto yy107;
			} else {
				if(yych <= 'n')	goto yy105;
				if(yych <= 'q')	goto yy107;
				goto yy105;
			}
		} else {
			if(yych <= 'u'){
				if(yych == 't')	goto yy105;
				goto yy107;
			} else {
				if(yych <= 'v')	goto yy105;
				if(yych == 'x')	goto yy111;
				goto yy107;
			}
		}
	}
yy109:	yych = *++YYCURSOR;
	goto yy110;
yy110:
#line 148 "cnokw.re"
{ RET(SCON); }
#line 675 "cnokw.c"
yy111:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy107;
		if(yych <= '9')	goto yy114;
		goto yy107;
	} else {
		if(yych <= 'F')	goto yy114;
		if(yych <= '`')	goto yy107;
		if(yych <= 'f')	goto yy114;
		goto yy107;
	}
yy112:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy113;
yy113:	if(yych <= '"'){
		if(yych == '\n')	goto yy107;
		if(yych <= '!')	goto yy105;
		goto yy109;
	} else {
		if(yych <= '7'){
			if(yych <= '/')	goto yy105;
			goto yy112;
		} else {
			if(yych == '\\')	goto yy108;
			goto yy105;
		}
	}
yy114:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy115;
yy115:	if(yych <= '9'){
		if(yych <= '!'){
			if(yych == '\n')	goto yy107;
			goto yy105;
		} else {
			if(yych <= '"')	goto yy109;
			if(yych <= '/')	goto yy105;
			goto yy114;
		}
	} else {
		if(yych <= '['){
			if(yych <= '@')	goto yy105;
			if(yych <= 'F')	goto yy114;
			goto yy105;
		} else {
			if(yych <= '\\')	goto yy108;
			if(yych <= '`')	goto yy105;
			if(yych <= 'f')	goto yy114;
			goto yy105;
		}
	}
yy116:	yych = *++YYCURSOR;
	if(yych == '.')	goto yy125;
	goto yy107;
yy117:	yyaccept = 3;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	goto yy118;
yy118:	if(yych <= 'K'){
		if(yych <= 'D'){
			if(yych <= '/')	goto yy119;
			if(yych <= '9')	goto yy117;
			goto yy119;
		} else {
			if(yych <= 'E')	goto yy120;
			if(yych <= 'F')	goto yy121;
			goto yy119;
		}
	} else {
		if(yych <= 'e'){
			if(yych <= 'L')	goto yy121;
			if(yych >= 'e')	goto yy120;
			goto yy119;
		} else {
			if(yych <= 'f')	goto yy121;
			if(yych == 'l')	goto yy121;
			goto yy119;
		}
	}
yy119:
#line 145 "cnokw.re"
{ RET(FCON); }
#line 763 "cnokw.c"
yy120:	yych = *++YYCURSOR;
	if(yych <= ','){
		if(yych == '+')	goto yy122;
		goto yy107;
	} else {
		if(yych <= '-')	goto yy122;
		if(yych <= '/')	goto yy107;
		if(yych <= '9')	goto yy123;
		goto yy107;
	}
yy121:	yych = *++YYCURSOR;
	goto yy119;
yy122:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy107;
	if(yych >= ':')	goto yy107;
	goto yy123;
yy123:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy124;
yy124:	if(yych <= 'K'){
		if(yych <= '9'){
			if(yych <= '/')	goto yy119;
			goto yy123;
		} else {
			if(yych == 'F')	goto yy121;
			goto yy119;
		}
	} else {
		if(yych <= 'f'){
			if(yych <= 'L')	goto yy121;
			if(yych <= 'e')	goto yy119;
			goto yy121;
		} else {
			if(yych == 'l')	goto yy121;
			goto yy119;
		}
	}
yy125:	yych = *++YYCURSOR;
	goto yy126;
yy126:
#line 150 "cnokw.re"
{ RET(ELLIPSIS); }
#line 807 "cnokw.c"
yy127:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy128;
yy128:	if(yych <= '&'){
		if(yych == '\n')	goto yy107;
		goto yy127;
	} else {
		if(yych <= '\'')	goto yy130;
		if(yych != '\\')	goto yy127;
		goto yy129;
	}
yy129:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= 'b'){
		if(yych <= '7'){
			if(yych <= '&'){
				if(yych == '"')	goto yy127;
				goto yy107;
			} else {
				if(yych <= '\'')	goto yy127;
				if(yych <= '/')	goto yy107;
				goto yy132;
			}
		} else {
			if(yych <= '['){
				if(yych == '?')	goto yy127;
				goto yy107;
			} else {
				if(yych <= '\\')	goto yy127;
				if(yych <= '`')	goto yy107;
				goto yy127;
			}
		}
	} else {
		if(yych <= 'r'){
			if(yych <= 'm'){
				if(yych == 'f')	goto yy127;
				goto yy107;
			} else {
				if(yych <= 'n')	goto yy127;
				if(yych <= 'q')	goto yy107;
				goto yy127;
			}
		} else {
			if(yych <= 'u'){
				if(yych == 't')	goto yy127;
				goto yy107;
			} else {
				if(yych <= 'v')	goto yy127;
				if(yych == 'x')	goto yy131;
				goto yy107;
			}
		}
	}
yy130:	yych = *++YYCURSOR;
	goto yy7;
yy131:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy107;
		if(yych <= '9')	goto yy134;
		goto yy107;
	} else {
		if(yych <= 'F')	goto yy134;
		if(yych <= '`')	goto yy107;
		if(yych <= 'f')	goto yy134;
		goto yy107;
	}
yy132:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy133;
yy133:	if(yych <= '\''){
		if(yych == '\n')	goto yy107;
		if(yych <= '&')	goto yy127;
		goto yy130;
	} else {
		if(yych <= '7'){
			if(yych <= '/')	goto yy127;
			goto yy132;
		} else {
			if(yych == '\\')	goto yy129;
			goto yy127;
		}
	}
yy134:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy135;
yy135:	if(yych <= '9'){
		if(yych <= '&'){
			if(yych == '\n')	goto yy107;
			goto yy127;
		} else {
			if(yych <= '\'')	goto yy130;
			if(yych <= '/')	goto yy127;
			goto yy134;
		}
	} else {
		if(yych <= '['){
			if(yych <= '@')	goto yy127;
			if(yych <= 'F')	goto yy134;
			goto yy127;
		} else {
			if(yych <= '\\')	goto yy129;
			if(yych <= '`')	goto yy127;
			if(yych <= 'f')	goto yy134;
			goto yy127;
		}
	}
yy136:	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'E')	goto yy147;
	if(yych == 'e')	goto yy147;
	goto yy146;
yy137:	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	goto yy138;
yy138:	if(yych <= 'L'){
		if(yych <= '9'){
			if(yych == '.')	goto yy136;
			if(yych <= '/')	goto yy7;
			goto yy137;
		} else {
			if(yych == 'E')	goto yy139;
			if(yych <= 'K')	goto yy7;
			goto yy140;
		}
	} else {
		if(yych <= 'e'){
			if(yych == 'U')	goto yy140;
			if(yych <= 'd')	goto yy7;
			goto yy139;
		} else {
			if(yych <= 'l'){
				if(yych <= 'k')	goto yy7;
				goto yy140;
			} else {
				if(yych == 'u')	goto yy140;
				goto yy7;
			}
		}
	}
yy139:	yych = *++YYCURSOR;
	if(yych <= ','){
		if(yych == '+')	goto yy142;
		goto yy107;
	} else {
		if(yych <= '-')	goto yy142;
		if(yych <= '/')	goto yy107;
		if(yych <= '9')	goto yy143;
		goto yy107;
	}
yy140:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy141;
yy141:	if(yych <= 'U'){
		if(yych == 'L')	goto yy140;
		if(yych <= 'T')	goto yy7;
		goto yy140;
	} else {
		if(yych <= 'l'){
			if(yych <= 'k')	goto yy7;
			goto yy140;
		} else {
			if(yych == 'u')	goto yy140;
			goto yy7;
		}
	}
yy142:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy107;
	if(yych >= ':')	goto yy107;
	goto yy143;
yy143:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy144;
yy144:	if(yych <= 'K'){
		if(yych <= '9'){
			if(yych <= '/')	goto yy119;
			goto yy143;
		} else {
			if(yych == 'F')	goto yy121;
			goto yy119;
		}
	} else {
		if(yych <= 'f'){
			if(yych <= 'L')	goto yy121;
			if(yych <= 'e')	goto yy119;
			goto yy121;
		} else {
			if(yych == 'l')	goto yy121;
			goto yy119;
		}
	}
yy145:	yyaccept = 3;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	goto yy146;
yy146:	if(yych <= 'K'){
		if(yych <= 'D'){
			if(yych <= '/')	goto yy119;
			if(yych <= '9')	goto yy145;
			goto yy119;
		} else {
			if(yych <= 'E')	goto yy151;
			if(yych <= 'F')	goto yy121;
			goto yy119;
		}
	} else {
		if(yych <= 'e'){
			if(yych <= 'L')	goto yy121;
			if(yych <= 'd')	goto yy119;
			goto yy151;
		} else {
			if(yych <= 'f')	goto yy121;
			if(yych == 'l')	goto yy121;
			goto yy119;
		}
	}
yy147:	yych = *++YYCURSOR;
	if(yych <= ','){
		if(yych != '+')	goto yy107;
		goto yy148;
	} else {
		if(yych <= '-')	goto yy148;
		if(yych <= '/')	goto yy107;
		if(yych <= '9')	goto yy149;
		goto yy107;
	}
yy148:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy107;
	if(yych >= ':')	goto yy107;
	goto yy149;
yy149:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy150;
yy150:	if(yych <= 'K'){
		if(yych <= '9'){
			if(yych <= '/')	goto yy119;
			goto yy149;
		} else {
			if(yych == 'F')	goto yy121;
			goto yy119;
		}
	} else {
		if(yych <= 'f'){
			if(yych <= 'L')	goto yy121;
			if(yych <= 'e')	goto yy119;
			goto yy121;
		} else {
			if(yych == 'l')	goto yy121;
			goto yy119;
		}
	}
yy151:	yych = *++YYCURSOR;
	if(yych <= ','){
		if(yych != '+')	goto yy107;
		goto yy152;
	} else {
		if(yych <= '-')	goto yy152;
		if(yych <= '/')	goto yy107;
		if(yych <= '9')	goto yy153;
		goto yy107;
	}
yy152:	yych = *++YYCURSOR;
	if(yych <= '/')	goto yy107;
	if(yych >= ':')	goto yy107;
	goto yy153;
yy153:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy154;
yy154:	if(yych <= 'K'){
		if(yych <= '9'){
			if(yych <= '/')	goto yy119;
			goto yy153;
		} else {
			if(yych == 'F')	goto yy121;
			goto yy119;
		}
	} else {
		if(yych <= 'f'){
			if(yych <= 'L')	goto yy121;
			if(yych <= 'e')	goto yy119;
			goto yy121;
		} else {
			if(yych == 'l')	goto yy121;
			goto yy119;
		}
	}
yy155:	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	goto yy156;
yy156:	if(yych <= 'L'){
		if(yych <= '9'){
			if(yych == '.')	goto yy136;
			if(yych <= '/')	goto yy7;
			goto yy155;
		} else {
			if(yych == 'E')	goto yy139;
			if(yych <= 'K')	goto yy7;
			goto yy162;
		}
	} else {
		if(yych <= 'e'){
			if(yych == 'U')	goto yy162;
			if(yych <= 'd')	goto yy7;
			goto yy139;
		} else {
			if(yych <= 'l'){
				if(yych <= 'k')	goto yy7;
				goto yy162;
			} else {
				if(yych == 'u')	goto yy162;
				goto yy7;
			}
		}
	}
yy157:	yych = *++YYCURSOR;
	if(yych <= '@'){
		if(yych <= '/')	goto yy107;
		if(yych >= ':')	goto yy107;
		goto yy158;
	} else {
		if(yych <= 'F')	goto yy158;
		if(yych <= '`')	goto yy107;
		if(yych >= 'g')	goto yy107;
		goto yy158;
	}
yy158:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy159;
yy159:	if(yych <= 'T'){
		if(yych <= '@'){
			if(yych <= '/')	goto yy7;
			if(yych <= '9')	goto yy158;
			goto yy7;
		} else {
			if(yych <= 'F')	goto yy158;
			if(yych != 'L')	goto yy7;
			goto yy160;
		}
	} else {
		if(yych <= 'k'){
			if(yych <= 'U')	goto yy160;
			if(yych <= '`')	goto yy7;
			if(yych <= 'f')	goto yy158;
			goto yy7;
		} else {
			if(yych <= 'l')	goto yy160;
			if(yych != 'u')	goto yy7;
			goto yy160;
		}
	}
yy160:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy161;
yy161:	if(yych <= 'U'){
		if(yych == 'L')	goto yy160;
		if(yych <= 'T')	goto yy7;
		goto yy160;
	} else {
		if(yych <= 'l'){
			if(yych <= 'k')	goto yy7;
			goto yy160;
		} else {
			if(yych == 'u')	goto yy160;
			goto yy7;
		}
	}
yy162:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy163;
yy163:	if(yych <= 'U'){
		if(yych == 'L')	goto yy162;
		if(yych <= 'T')	goto yy7;
		goto yy162;
	} else {
		if(yych <= 'l'){
			if(yych <= 'k')	goto yy7;
			goto yy162;
		} else {
			if(yych == 'u')	goto yy162;
			goto yy7;
		}
	}
yy164:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	goto yy165;
yy165:	if(yych <= 'Z'){
		if(yych <= '/')	goto yy5;
		if(yych <= '9')	goto yy164;
		if(yych <= '@')	goto yy5;
		goto yy164;
	} else {
		if(yych <= '_'){
			if(yych <= '^')	goto yy5;
			goto yy164;
		} else {
			if(yych <= '`')	goto yy5;
			if(yych <= 'z')	goto yy164;
			goto yy5;
		}
	}
yy166:	yych = *++YYCURSOR;
	goto yy167;
yy167:
#line 156 "cnokw.re"
{ RET(DIVEQ); }
#line 1232 "cnokw.c"
yy168:	yych = *++YYCURSOR;
	goto yy169;
yy169:
#line 136 "cnokw.re"
{ goto comment; }
#line 1238 "cnokw.c"
}
#line 212 "cnokw.re"


comment:

#line 1245 "cnokw.c"
{
	YYCTYPE yych;
	goto yy170;
	++YYCURSOR;
yy170:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych == '\n')	goto yy174;
	if(yych != '*')	goto yy176;
	goto yy172;
yy172:	yych = *++YYCURSOR;
	if(yych == '/')	goto yy177;
	goto yy173;
yy173:
#line 223 "cnokw.re"
{ goto comment; }
#line 1262 "cnokw.c"
yy174:	yych = *++YYCURSOR;
	goto yy175;
yy175:
#line 218 "cnokw.re"
{
		if(cursor == s->eof) RET(EOI);
		s->tok = s->pos = cursor; s->line++;
		goto comment;
	    }
#line 1272 "cnokw.c"
yy176:	yych = *++YYCURSOR;
	goto yy173;
yy177:	yych = *++YYCURSOR;
	goto yy178;
yy178:
#line 216 "cnokw.re"
{ goto std; }
#line 1280 "cnokw.c"
}
#line 224 "cnokw.re"

}

main(){
    Scanner in;
    int t;
    memset((char*) &in, 0, sizeof(in));
    in.fd = 0;
    while((t = scan(&in)) != EOI){
/*
	printf("%d\t%.*s\n", t, in.cur - in.tok, in.tok);
	printf("%d\n", t);
*/
    }
    close(in.fd);
}
